// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfacesmock

import (
	context "context"

	consentelementmodel "github.com/wso2/openfgc/consent-server/internal/consentelement/model"

	mock "github.com/stretchr/testify/mock"

	model "github.com/wso2/openfgc/consent-server/internal/system/database/model"
)

// ConsentElementStore is an autogenerated mock type for the ConsentElementStore type
type ConsentElementStore struct {
	mock.Mock
}

// CreateVersion provides a mock function with given fields: tx, version
func (_m *ConsentElementStore) CreateVersion(tx model.TxInterface, version *consentelementmodel.ElementVersion) error {
	ret := _m.Called(tx, version)

	if len(ret) == 0 {
		panic("no return value specified for CreateVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentelementmodel.ElementVersion) error); ok {
		r0 = rf(tx, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteElement provides a mock function with given fields: tx, elementID, orgID
func (_m *ConsentElementStore) DeleteElement(tx model.TxInterface, elementID string, orgID string) error {
	ret := _m.Called(tx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteElement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, elementID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteVersion provides a mock function with given fields: tx, versionID, orgID
func (_m *ConsentElementStore) DeleteVersion(tx model.TxInterface, versionID string, orgID string) error {
	ret := _m.Called(tx, versionID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, versionID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ElementExists provides a mock function with given fields: ctx, elementID, orgID
func (_m *ConsentElementStore) ElementExists(ctx context.Context, elementID string, orgID string) (bool, error) {
	ret := _m.Called(ctx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ElementExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, elementID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, elementID, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, elementID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByNameAndNamespace provides a mock function with given fields: ctx, name, namespace, orgID
func (_m *ConsentElementStore) GetByNameAndNamespace(ctx context.Context, name string, namespace string, orgID string) (*consentelementmodel.ElementVersion, error) {
	ret := _m.Called(ctx, name, namespace, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByNameAndNamespace")
	}

	var r0 *consentelementmodel.ElementVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*consentelementmodel.ElementVersion, error)); ok {
		return rf(ctx, name, namespace, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *consentelementmodel.ElementVersion); ok {
		r0 = rf(ctx, name, namespace, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentelementmodel.ElementVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, name, namespace, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestVersion provides a mock function with given fields: ctx, elementID, orgID
func (_m *ConsentElementStore) GetLatestVersion(ctx context.Context, elementID string, orgID string) (*consentelementmodel.ElementVersion, error) {
	ret := _m.Called(ctx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 *consentelementmodel.ElementVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*consentelementmodel.ElementVersion, error)); ok {
		return rf(ctx, elementID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *consentelementmodel.ElementVersion); ok {
		r0 = rf(ctx, elementID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentelementmodel.ElementVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, elementID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVersion provides a mock function with given fields: ctx, elementID, version, orgID
func (_m *ConsentElementStore) GetVersion(ctx context.Context, elementID string, version int, orgID string) (*consentelementmodel.ElementVersion, error) {
	ret := _m.Called(ctx, elementID, version, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 *consentelementmodel.ElementVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) (*consentelementmodel.ElementVersion, error)); ok {
		return rf(ctx, elementID, version, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) *consentelementmodel.ElementVersion); ok {
		r0 = rf(ctx, elementID, version, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentelementmodel.ElementVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, string) error); ok {
		r1 = rf(ctx, elementID, version, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsVersionReferencedByPurpose provides a mock function with given fields: ctx, versionID, orgID
func (_m *ConsentElementStore) IsVersionReferencedByPurpose(ctx context.Context, versionID string, orgID string) (bool, error) {
	ret := _m.Called(ctx, versionID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for IsVersionReferencedByPurpose")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, versionID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, versionID, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, versionID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, orgID, filters
func (_m *ConsentElementStore) List(ctx context.Context, orgID string, filters consentelementmodel.ElementListFilter) ([]consentelementmodel.ElementVersion, int, error) {
	ret := _m.Called(ctx, orgID, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []consentelementmodel.ElementVersion
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, consentelementmodel.ElementListFilter) ([]consentelementmodel.ElementVersion, int, error)); ok {
		return rf(ctx, orgID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, consentelementmodel.ElementListFilter) []consentelementmodel.ElementVersion); ok {
		r0 = rf(ctx, orgID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentelementmodel.ElementVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, consentelementmodel.ElementListFilter) int); ok {
		r1 = rf(ctx, orgID, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, consentelementmodel.ElementListFilter) error); ok {
		r2 = rf(ctx, orgID, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListVersions provides a mock function with given fields: ctx, elementID, orgID
func (_m *ConsentElementStore) ListVersions(ctx context.Context, elementID string, orgID string) ([]consentelementmodel.ElementVersion, error) {
	ret := _m.Called(ctx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListVersions")
	}

	var r0 []consentelementmodel.ElementVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentelementmodel.ElementVersion, error)); ok {
		return rf(ctx, elementID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentelementmodel.ElementVersion); ok {
		r0 = rf(ctx, elementID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentelementmodel.ElementVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, elementID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewConsentElementStore creates a new instance of ConsentElementStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentElementStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentElementStore {
	mock := &ConsentElementStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
