// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfacesmock

import (
	context "context"

	consentpurposemodel "github.com/wso2/openfgc/consent-server/internal/consentpurpose/model"

	mock "github.com/stretchr/testify/mock"

	model "github.com/wso2/openfgc/consent-server/internal/system/database/model"
)

// ConsentPurposeStore is an autogenerated mock type for the ConsentPurposeStore type
type ConsentPurposeStore struct {
	mock.Mock
}

// CreateVersion provides a mock function with given fields: tx, version
func (_m *ConsentPurposeStore) CreateVersion(tx model.TxInterface, version *consentpurposemodel.PurposeVersion) error {
	ret := _m.Called(tx, version)

	if len(ret) == 0 {
		panic("no return value specified for CreateVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentpurposemodel.PurposeVersion) error); ok {
		r0 = rf(tx, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePurpose provides a mock function with given fields: tx, purposeID, orgID
func (_m *ConsentPurposeStore) DeletePurpose(tx model.TxInterface, purposeID string, orgID string) error {
	ret := _m.Called(tx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurpose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, purposeID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteVersion provides a mock function with given fields: tx, purposeVersionID, orgID
func (_m *ConsentPurposeStore) DeleteVersion(tx model.TxInterface, purposeVersionID string, orgID string) error {
	ret := _m.Called(tx, purposeVersionID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, purposeVersionID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByNameAndGroupID provides a mock function with given fields: ctx, name, groupID, orgID
func (_m *ConsentPurposeStore) GetByNameAndGroupID(ctx context.Context, name string, groupID string, orgID string) (*consentpurposemodel.PurposeVersion, error) {
	ret := _m.Called(ctx, name, groupID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByNameAndGroupID")
	}

	var r0 *consentpurposemodel.PurposeVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*consentpurposemodel.PurposeVersion, error)); ok {
		return rf(ctx, name, groupID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *consentpurposemodel.PurposeVersion); ok {
		r0 = rf(ctx, name, groupID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentpurposemodel.PurposeVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, name, groupID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestVersion provides a mock function with given fields: ctx, purposeID, orgID
func (_m *ConsentPurposeStore) GetLatestVersion(ctx context.Context, purposeID string, orgID string) (*consentpurposemodel.PurposeVersion, error) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 *consentpurposemodel.PurposeVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*consentpurposemodel.PurposeVersion, error)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *consentpurposemodel.PurposeVersion); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentpurposemodel.PurposeVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVersion provides a mock function with given fields: ctx, purposeID, version, orgID
func (_m *ConsentPurposeStore) GetVersion(ctx context.Context, purposeID string, version int, orgID string) (*consentpurposemodel.PurposeVersion, error) {
	ret := _m.Called(ctx, purposeID, version, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 *consentpurposemodel.PurposeVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) (*consentpurposemodel.PurposeVersion, error)); ok {
		return rf(ctx, purposeID, version, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) *consentpurposemodel.PurposeVersion); ok {
		r0 = rf(ctx, purposeID, version, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentpurposemodel.PurposeVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, string) error); ok {
		r1 = rf(ctx, purposeID, version, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVersionByID provides a mock function with given fields: ctx, purposeVersionID, orgID
func (_m *ConsentPurposeStore) GetVersionByID(ctx context.Context, purposeVersionID string, orgID string) (*consentpurposemodel.PurposeVersion, error) {
	ret := _m.Called(ctx, purposeVersionID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetVersionByID")
	}

	var r0 *consentpurposemodel.PurposeVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*consentpurposemodel.PurposeVersion, error)); ok {
		return rf(ctx, purposeVersionID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *consentpurposemodel.PurposeVersion); ok {
		r0 = rf(ctx, purposeVersionID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentpurposemodel.PurposeVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeVersionID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVersionElements provides a mock function with given fields: ctx, purposeVersionID, orgID
func (_m *ConsentPurposeStore) GetVersionElements(ctx context.Context, purposeVersionID string, orgID string) ([]consentpurposemodel.PurposeMappedElement, error) {
	ret := _m.Called(ctx, purposeVersionID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetVersionElements")
	}

	var r0 []consentpurposemodel.PurposeMappedElement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentpurposemodel.PurposeMappedElement, error)); ok {
		return rf(ctx, purposeVersionID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentpurposemodel.PurposeMappedElement); ok {
		r0 = rf(ctx, purposeVersionID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentpurposemodel.PurposeMappedElement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeVersionID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsElementVersionUsed provides a mock function with given fields: ctx, elementVersionID, orgID
func (_m *ConsentPurposeStore) IsElementVersionUsed(ctx context.Context, elementVersionID string, orgID string) (bool, error) {
	ret := _m.Called(ctx, elementVersionID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for IsElementVersionUsed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, elementVersionID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, elementVersionID, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, elementVersionID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsVersionUsedInConsents provides a mock function with given fields: ctx, purposeVersionID, orgID
func (_m *ConsentPurposeStore) IsVersionUsedInConsents(ctx context.Context, purposeVersionID string, orgID string) (bool, error) {
	ret := _m.Called(ctx, purposeVersionID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for IsVersionUsedInConsents")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, purposeVersionID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, purposeVersionID, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeVersionID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkElementVersion provides a mock function with given fields: tx, purposeVersionID, elementVersionID, orgID, mandatory
func (_m *ConsentPurposeStore) LinkElementVersion(tx model.TxInterface, purposeVersionID string, elementVersionID string, orgID string, mandatory bool) error {
	ret := _m.Called(tx, purposeVersionID, elementVersionID, orgID, mandatory)

	if len(ret) == 0 {
		panic("no return value specified for LinkElementVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string, string, bool) error); ok {
		r0 = rf(tx, purposeVersionID, elementVersionID, orgID, mandatory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, orgID, filters
func (_m *ConsentPurposeStore) List(ctx context.Context, orgID string, filters consentpurposemodel.PurposeListFilter) ([]consentpurposemodel.PurposeVersion, int, error) {
	ret := _m.Called(ctx, orgID, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []consentpurposemodel.PurposeVersion
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, consentpurposemodel.PurposeListFilter) ([]consentpurposemodel.PurposeVersion, int, error)); ok {
		return rf(ctx, orgID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, consentpurposemodel.PurposeListFilter) []consentpurposemodel.PurposeVersion); ok {
		r0 = rf(ctx, orgID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentpurposemodel.PurposeVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, consentpurposemodel.PurposeListFilter) int); ok {
		r1 = rf(ctx, orgID, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, consentpurposemodel.PurposeListFilter) error); ok {
		r2 = rf(ctx, orgID, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListVersions provides a mock function with given fields: ctx, purposeID, orgID
func (_m *ConsentPurposeStore) ListVersions(ctx context.Context, purposeID string, orgID string) ([]consentpurposemodel.PurposeVersion, error) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListVersions")
	}

	var r0 []consentpurposemodel.PurposeVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentpurposemodel.PurposeVersion, error)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentpurposemodel.PurposeVersion); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentpurposemodel.PurposeVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PurposeExists provides a mock function with given fields: ctx, purposeID, orgID
func (_m *ConsentPurposeStore) PurposeExists(ctx context.Context, purposeID string, orgID string) (bool, error) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for PurposeExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsByNameInOrg provides a mock function with given fields: ctx, name, orgID
func (_m *ConsentPurposeStore) ExistsByNameInOrg(ctx context.Context, name string, orgID string) (bool, error) {
	ret := _m.Called(ctx, name, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByNameInOrg")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, name, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, name, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewConsentPurposeStore creates a new instance of ConsentPurposeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentPurposeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentPurposeStore {
	mock := &ConsentPurposeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
