// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfacesmock

import (
	context "context"

	consentmodel "github.com/wso2/openfgc/internal/consent/model"

	mock "github.com/stretchr/testify/mock"

	model "github.com/wso2/openfgc/internal/system/database/model"
)

// ConsentStore is an autogenerated mock type for the ConsentStore type
type ConsentStore struct {
	mock.Mock
}

type ConsentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsentStore) EXPECT() *ConsentStore_Expecter {
	return &ConsentStore_Expecter{mock: &_m.Mock}
}

// CheckPurposeUsedInConsents provides a mock function with given fields: ctx, purposeID, orgID
func (_m *ConsentStore) CheckPurposeUsedInConsents(ctx context.Context, purposeID string, orgID string) (bool, error) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CheckPurposeUsedInConsents")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_CheckPurposeUsedInConsents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPurposeUsedInConsents'
type ConsentStore_CheckPurposeUsedInConsents_Call struct {
	*mock.Call
}

// CheckPurposeUsedInConsents is a helper method to define mock.On call
//   - ctx context.Context
//   - purposeID string
//   - orgID string
func (_e *ConsentStore_Expecter) CheckPurposeUsedInConsents(ctx interface{}, purposeID interface{}, orgID interface{}) *ConsentStore_CheckPurposeUsedInConsents_Call {
	return &ConsentStore_CheckPurposeUsedInConsents_Call{Call: _e.mock.On("CheckPurposeUsedInConsents", ctx, purposeID, orgID)}
}

func (_c *ConsentStore_CheckPurposeUsedInConsents_Call) Run(run func(ctx context.Context, purposeID string, orgID string)) *ConsentStore_CheckPurposeUsedInConsents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_CheckPurposeUsedInConsents_Call) Return(_a0 bool, _a1 error) *ConsentStore_CheckPurposeUsedInConsents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_CheckPurposeUsedInConsents_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *ConsentStore_CheckPurposeUsedInConsents_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: tx, consent
func (_m *ConsentStore) Create(tx model.TxInterface, consent *consentmodel.Consent) error {
	ret := _m.Called(tx, consent)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.Consent) error); ok {
		r0 = rf(tx, consent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ConsentStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consent *consentmodel.Consent
func (_e *ConsentStore_Expecter) Create(tx interface{}, consent interface{}) *ConsentStore_Create_Call {
	return &ConsentStore_Create_Call{Call: _e.mock.On("Create", tx, consent)}
}

func (_c *ConsentStore_Create_Call) Run(run func(tx model.TxInterface, consent *consentmodel.Consent)) *ConsentStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.Consent))
	})
	return _c
}

func (_c *ConsentStore_Create_Call) Return(_a0 error) *ConsentStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_Create_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.Consent) error) *ConsentStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAttributes provides a mock function with given fields: tx, attributes
func (_m *ConsentStore) CreateAttributes(tx model.TxInterface, attributes []consentmodel.ConsentAttribute) error {
	ret := _m.Called(tx, attributes)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttributes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, []consentmodel.ConsentAttribute) error); ok {
		r0 = rf(tx, attributes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreateAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAttributes'
type ConsentStore_CreateAttributes_Call struct {
	*mock.Call
}

// CreateAttributes is a helper method to define mock.On call
//   - tx model.TxInterface
//   - attributes []consentmodel.ConsentAttribute
func (_e *ConsentStore_Expecter) CreateAttributes(tx interface{}, attributes interface{}) *ConsentStore_CreateAttributes_Call {
	return &ConsentStore_CreateAttributes_Call{Call: _e.mock.On("CreateAttributes", tx, attributes)}
}

func (_c *ConsentStore_CreateAttributes_Call) Run(run func(tx model.TxInterface, attributes []consentmodel.ConsentAttribute)) *ConsentStore_CreateAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].([]consentmodel.ConsentAttribute))
	})
	return _c
}

func (_c *ConsentStore_CreateAttributes_Call) Return(_a0 error) *ConsentStore_CreateAttributes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreateAttributes_Call) RunAndReturn(run func(model.TxInterface, []consentmodel.ConsentAttribute) error) *ConsentStore_CreateAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// CreateConsentPurposeConsent provides a mock function with given fields: tx, consentID, purposeID, orgID
func (_m *ConsentStore) CreateConsentPurposeConsent(tx model.TxInterface, consentID string, purposeID string, orgID string) error {
	ret := _m.Called(tx, consentID, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CreateConsentPurposeConsent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string, string) error); ok {
		r0 = rf(tx, consentID, purposeID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreateConsentPurposeConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConsentPurposeConsent'
type ConsentStore_CreateConsentPurposeConsent_Call struct {
	*mock.Call
}

// CreateConsentPurposeConsent is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - purposeID string
//   - orgID string
func (_e *ConsentStore_Expecter) CreateConsentPurposeConsent(tx interface{}, consentID interface{}, purposeID interface{}, orgID interface{}) *ConsentStore_CreateConsentPurposeConsent_Call {
	return &ConsentStore_CreateConsentPurposeConsent_Call{Call: _e.mock.On("CreateConsentPurposeConsent", tx, consentID, purposeID, orgID)}
}

func (_c *ConsentStore_CreateConsentPurposeConsent_Call) Run(run func(tx model.TxInterface, consentID string, purposeID string, orgID string)) *ConsentStore_CreateConsentPurposeConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ConsentStore_CreateConsentPurposeConsent_Call) Return(_a0 error) *ConsentStore_CreateConsentPurposeConsent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreateConsentPurposeConsent_Call) RunAndReturn(run func(model.TxInterface, string, string, string) error) *ConsentStore_CreateConsentPurposeConsent_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePurposeApproval provides a mock function with given fields: tx, approval
func (_m *ConsentStore) CreatePurposeApproval(tx model.TxInterface, approval *consentmodel.ConsentElementApprovalRecord) error {
	ret := _m.Called(tx, approval)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurposeApproval")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.ConsentElementApprovalRecord) error); ok {
		r0 = rf(tx, approval)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreatePurposeApproval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePurposeApproval'
type ConsentStore_CreatePurposeApproval_Call struct {
	*mock.Call
}

// CreatePurposeApproval is a helper method to define mock.On call
//   - tx model.TxInterface
//   - approval *consentmodel.ConsentPurposeApprovalRecord
func (_e *ConsentStore_Expecter) CreatePurposeApproval(tx interface{}, approval interface{}) *ConsentStore_CreatePurposeApproval_Call {
	return &ConsentStore_CreatePurposeApproval_Call{Call: _e.mock.On("CreatePurposeApproval", tx, approval)}
}

func (_c *ConsentStore_CreatePurposeApproval_Call) Run(run func(tx model.TxInterface, approval *consentmodel.ConsentElementApprovalRecord)) *ConsentStore_CreatePurposeApproval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.ConsentElementApprovalRecord))
	})
	return _c
}

func (_c *ConsentStore_CreatePurposeApproval_Call) Return(_a0 error) *ConsentStore_CreatePurposeApproval_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreatePurposeApproval_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.ConsentElementApprovalRecord) error) *ConsentStore_CreatePurposeApproval_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStatusAudit provides a mock function with given fields: tx, audit
func (_m *ConsentStore) CreateStatusAudit(tx model.TxInterface, audit *consentmodel.ConsentStatusAudit) error {
	ret := _m.Called(tx, audit)

	if len(ret) == 0 {
		panic("no return value specified for CreateStatusAudit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.ConsentStatusAudit) error); ok {
		r0 = rf(tx, audit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreateStatusAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStatusAudit'
type ConsentStore_CreateStatusAudit_Call struct {
	*mock.Call
}

// CreateStatusAudit is a helper method to define mock.On call
//   - tx model.TxInterface
//   - audit *consentmodel.ConsentStatusAudit
func (_e *ConsentStore_Expecter) CreateStatusAudit(tx interface{}, audit interface{}) *ConsentStore_CreateStatusAudit_Call {
	return &ConsentStore_CreateStatusAudit_Call{Call: _e.mock.On("CreateStatusAudit", tx, audit)}
}

func (_c *ConsentStore_CreateStatusAudit_Call) Run(run func(tx model.TxInterface, audit *consentmodel.ConsentStatusAudit)) *ConsentStore_CreateStatusAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.ConsentStatusAudit))
	})
	return _c
}

func (_c *ConsentStore_CreateStatusAudit_Call) Return(_a0 error) *ConsentStore_CreateStatusAudit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreateStatusAudit_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.ConsentStatusAudit) error) *ConsentStore_CreateStatusAudit_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: tx, consentID, orgID
func (_m *ConsentStore) Delete(tx model.TxInterface, consentID string, orgID string) error {
	ret := _m.Called(tx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, consentID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ConsentStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) Delete(tx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_Delete_Call {
	return &ConsentStore_Delete_Call{Call: _e.mock.On("Delete", tx, consentID, orgID)}
}

func (_c *ConsentStore_Delete_Call) Run(run func(tx model.TxInterface, consentID string, orgID string)) *ConsentStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_Delete_Call) Return(_a0 error) *ConsentStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_Delete_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttributesByConsentID provides a mock function with given fields: tx, consentID, orgID
func (_m *ConsentStore) DeleteAttributesByConsentID(tx model.TxInterface, consentID string, orgID string) error {
	ret := _m.Called(tx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttributesByConsentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, consentID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_DeleteAttributesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttributesByConsentID'
type ConsentStore_DeleteAttributesByConsentID_Call struct {
	*mock.Call
}

// DeleteAttributesByConsentID is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) DeleteAttributesByConsentID(tx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_DeleteAttributesByConsentID_Call {
	return &ConsentStore_DeleteAttributesByConsentID_Call{Call: _e.mock.On("DeleteAttributesByConsentID", tx, consentID, orgID)}
}

func (_c *ConsentStore_DeleteAttributesByConsentID_Call) Run(run func(tx model.TxInterface, consentID string, orgID string)) *ConsentStore_DeleteAttributesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_DeleteAttributesByConsentID_Call) Return(_a0 error) *ConsentStore_DeleteAttributesByConsentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_DeleteAttributesByConsentID_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentStore_DeleteAttributesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteConsentPurposesByConsentID provides a mock function with given fields: tx, consentID, orgID
func (_m *ConsentStore) DeleteConsentPurposesByConsentID(tx model.TxInterface, consentID string, orgID string) error {
	ret := _m.Called(tx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConsentPurposesByConsentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, consentID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_DeleteConsentPurposesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConsentPurposesByConsentID'
type ConsentStore_DeleteConsentPurposesByConsentID_Call struct {
	*mock.Call
}

// DeleteConsentPurposesByConsentID is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) DeleteConsentPurposesByConsentID(tx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_DeleteConsentPurposesByConsentID_Call {
	return &ConsentStore_DeleteConsentPurposesByConsentID_Call{Call: _e.mock.On("DeleteConsentPurposesByConsentID", tx, consentID, orgID)}
}

func (_c *ConsentStore_DeleteConsentPurposesByConsentID_Call) Run(run func(tx model.TxInterface, consentID string, orgID string)) *ConsentStore_DeleteConsentPurposesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_DeleteConsentPurposesByConsentID_Call) Return(_a0 error) *ConsentStore_DeleteConsentPurposesByConsentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_DeleteConsentPurposesByConsentID_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentStore_DeleteConsentPurposesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePurposeApprovalsByConsentID provides a mock function with given fields: tx, consentID, orgID
func (_m *ConsentStore) DeletePurposeApprovalsByConsentID(tx model.TxInterface, consentID string, orgID string) error {
	ret := _m.Called(tx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurposeApprovalsByConsentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, consentID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_DeletePurposeApprovalsByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePurposeApprovalsByConsentID'
type ConsentStore_DeletePurposeApprovalsByConsentID_Call struct {
	*mock.Call
}

// DeletePurposeApprovalsByConsentID is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) DeletePurposeApprovalsByConsentID(tx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_DeletePurposeApprovalsByConsentID_Call {
	return &ConsentStore_DeletePurposeApprovalsByConsentID_Call{Call: _e.mock.On("DeletePurposeApprovalsByConsentID", tx, consentID, orgID)}
}

func (_c *ConsentStore_DeletePurposeApprovalsByConsentID_Call) Run(run func(tx model.TxInterface, consentID string, orgID string)) *ConsentStore_DeletePurposeApprovalsByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_DeletePurposeApprovalsByConsentID_Call) Return(_a0 error) *ConsentStore_DeletePurposeApprovalsByConsentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_DeletePurposeApprovalsByConsentID_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentStore_DeletePurposeApprovalsByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// FindConsentIDsByAttribute provides a mock function with given fields: ctx, key, value, orgID
func (_m *ConsentStore) FindConsentIDsByAttribute(ctx context.Context, key string, value string, orgID string) ([]string, error) {
	ret := _m.Called(ctx, key, value, orgID)

	if len(ret) == 0 {
		panic("no return value specified for FindConsentIDsByAttribute")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]string, error)); ok {
		return rf(ctx, key, value, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []string); ok {
		r0 = rf(ctx, key, value, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, key, value, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_FindConsentIDsByAttribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindConsentIDsByAttribute'
type ConsentStore_FindConsentIDsByAttribute_Call struct {
	*mock.Call
}

// FindConsentIDsByAttribute is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - orgID string
func (_e *ConsentStore_Expecter) FindConsentIDsByAttribute(ctx interface{}, key interface{}, value interface{}, orgID interface{}) *ConsentStore_FindConsentIDsByAttribute_Call {
	return &ConsentStore_FindConsentIDsByAttribute_Call{Call: _e.mock.On("FindConsentIDsByAttribute", ctx, key, value, orgID)}
}

func (_c *ConsentStore_FindConsentIDsByAttribute_Call) Run(run func(ctx context.Context, key string, value string, orgID string)) *ConsentStore_FindConsentIDsByAttribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ConsentStore_FindConsentIDsByAttribute_Call) Return(_a0 []string, _a1 error) *ConsentStore_FindConsentIDsByAttribute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_FindConsentIDsByAttribute_Call) RunAndReturn(run func(context.Context, string, string, string) ([]string, error)) *ConsentStore_FindConsentIDsByAttribute_Call {
	_c.Call.Return(run)
	return _c
}

// FindConsentIDsByAttributeKey provides a mock function with given fields: ctx, key, orgID
func (_m *ConsentStore) FindConsentIDsByAttributeKey(ctx context.Context, key string, orgID string) ([]string, error) {
	ret := _m.Called(ctx, key, orgID)

	if len(ret) == 0 {
		panic("no return value specified for FindConsentIDsByAttributeKey")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, key, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, key, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_FindConsentIDsByAttributeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindConsentIDsByAttributeKey'
type ConsentStore_FindConsentIDsByAttributeKey_Call struct {
	*mock.Call
}

// FindConsentIDsByAttributeKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - orgID string
func (_e *ConsentStore_Expecter) FindConsentIDsByAttributeKey(ctx interface{}, key interface{}, orgID interface{}) *ConsentStore_FindConsentIDsByAttributeKey_Call {
	return &ConsentStore_FindConsentIDsByAttributeKey_Call{Call: _e.mock.On("FindConsentIDsByAttributeKey", ctx, key, orgID)}
}

func (_c *ConsentStore_FindConsentIDsByAttributeKey_Call) Run(run func(ctx context.Context, key string, orgID string)) *ConsentStore_FindConsentIDsByAttributeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_FindConsentIDsByAttributeKey_Call) Return(_a0 []string, _a1 error) *ConsentStore_FindConsentIDsByAttributeKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_FindConsentIDsByAttributeKey_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *ConsentStore_FindConsentIDsByAttributeKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttributesByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetAttributesByConsentID(ctx context.Context, consentID string, orgID string) ([]consentmodel.ConsentAttribute, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttributesByConsentID")
	}

	var r0 []consentmodel.ConsentAttribute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.ConsentAttribute, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.ConsentAttribute); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentAttribute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetAttributesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttributesByConsentID'
type ConsentStore_GetAttributesByConsentID_Call struct {
	*mock.Call
}

// GetAttributesByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetAttributesByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetAttributesByConsentID_Call {
	return &ConsentStore_GetAttributesByConsentID_Call{Call: _e.mock.On("GetAttributesByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetAttributesByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetAttributesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentID_Call) Return(_a0 []consentmodel.ConsentAttribute, _a1 error) *ConsentStore_GetAttributesByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.ConsentAttribute, error)) *ConsentStore_GetAttributesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttributesByConsentIDs provides a mock function with given fields: ctx, consentIDs, orgID
func (_m *ConsentStore) GetAttributesByConsentIDs(ctx context.Context, consentIDs []string, orgID string) (map[string]map[string]string, error) {
	ret := _m.Called(ctx, consentIDs, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttributesByConsentIDs")
	}

	var r0 map[string]map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) (map[string]map[string]string, error)); ok {
		return rf(ctx, consentIDs, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) map[string]map[string]string); ok {
		r0 = rf(ctx, consentIDs, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, consentIDs, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetAttributesByConsentIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttributesByConsentIDs'
type ConsentStore_GetAttributesByConsentIDs_Call struct {
	*mock.Call
}

// GetAttributesByConsentIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - consentIDs []string
//   - orgID string
func (_e *ConsentStore_Expecter) GetAttributesByConsentIDs(ctx interface{}, consentIDs interface{}, orgID interface{}) *ConsentStore_GetAttributesByConsentIDs_Call {
	return &ConsentStore_GetAttributesByConsentIDs_Call{Call: _e.mock.On("GetAttributesByConsentIDs", ctx, consentIDs, orgID)}
}

func (_c *ConsentStore_GetAttributesByConsentIDs_Call) Run(run func(ctx context.Context, consentIDs []string, orgID string)) *ConsentStore_GetAttributesByConsentIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentIDs_Call) Return(_a0 map[string]map[string]string, _a1 error) *ConsentStore_GetAttributesByConsentIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentIDs_Call) RunAndReturn(run func(context.Context, []string, string) (map[string]map[string]string, error)) *ConsentStore_GetAttributesByConsentIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetByClientID provides a mock function with given fields: ctx, clientID, orgID
func (_m *ConsentStore) GetByClientID(ctx context.Context, clientID string, orgID string) ([]consentmodel.Consent, error) {
	ret := _m.Called(ctx, clientID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByClientID")
	}

	var r0 []consentmodel.Consent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.Consent, error)); ok {
		return rf(ctx, clientID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.Consent); ok {
		r0 = rf(ctx, clientID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.Consent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, clientID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetByClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByClientID'
type ConsentStore_GetByClientID_Call struct {
	*mock.Call
}

// GetByClientID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetByClientID(ctx interface{}, clientID interface{}, orgID interface{}) *ConsentStore_GetByClientID_Call {
	return &ConsentStore_GetByClientID_Call{Call: _e.mock.On("GetByClientID", ctx, clientID, orgID)}
}

func (_c *ConsentStore_GetByClientID_Call) Run(run func(ctx context.Context, clientID string, orgID string)) *ConsentStore_GetByClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetByClientID_Call) Return(_a0 []consentmodel.Consent, _a1 error) *ConsentStore_GetByClientID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetByClientID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.Consent, error)) *ConsentStore_GetByClientID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetByID(ctx context.Context, consentID string, orgID string) (*consentmodel.Consent, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *consentmodel.Consent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*consentmodel.Consent, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *consentmodel.Consent); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentmodel.Consent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ConsentStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetByID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetByID_Call {
	return &ConsentStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetByID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetByID_Call) Return(_a0 *consentmodel.Consent, _a1 error) *ConsentStore_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*consentmodel.Consent, error)) *ConsentStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetConsentPurposesByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetConsentPurposesByConsentID(ctx context.Context, consentID string, orgID string) ([]consentmodel.ConsentPurposeMapping, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetConsentPurposesByConsentID")
	}

	var r0 []consentmodel.ConsentPurposeMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.ConsentPurposeMapping, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.ConsentPurposeMapping); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentPurposeMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetConsentPurposesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConsentPurposesByConsentID'
type ConsentStore_GetConsentPurposesByConsentID_Call struct {
	*mock.Call
}

// GetConsentPurposesByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetConsentPurposesByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetConsentPurposesByConsentID_Call {
	return &ConsentStore_GetConsentPurposesByConsentID_Call{Call: _e.mock.On("GetConsentPurposesByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetConsentPurposesByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetConsentPurposesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetConsentPurposesByConsentID_Call) Return(_a0 []consentmodel.ConsentPurposeMapping, _a1 error) *ConsentStore_GetConsentPurposesByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetConsentPurposesByConsentID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.ConsentPurposeMapping, error)) *ConsentStore_GetConsentPurposesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPurposeApprovalsByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetPurposeApprovalsByConsentID(ctx context.Context, consentID string, orgID string) ([]consentmodel.ConsentElementApprovalRecord, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposeApprovalsByConsentID")
	}

	var r0 []consentmodel.ConsentElementApprovalRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.ConsentElementApprovalRecord, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.ConsentElementApprovalRecord); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentElementApprovalRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetPurposeApprovalsByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPurposeApprovalsByConsentID'
type ConsentStore_GetPurposeApprovalsByConsentID_Call struct {
	*mock.Call
}

// GetPurposeApprovalsByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetPurposeApprovalsByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetPurposeApprovalsByConsentID_Call {
	return &ConsentStore_GetPurposeApprovalsByConsentID_Call{Call: _e.mock.On("GetPurposeApprovalsByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetPurposeApprovalsByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetPurposeApprovalsByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetPurposeApprovalsByConsentID_Call) Return(_a0 []consentmodel.ConsentElementApprovalRecord, _a1 error) *ConsentStore_GetPurposeApprovalsByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetPurposeApprovalsByConsentID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.ConsentElementApprovalRecord, error)) *ConsentStore_GetPurposeApprovalsByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusAuditByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetStatusAuditByConsentID(ctx context.Context, consentID string, orgID string) ([]consentmodel.ConsentStatusAudit, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusAuditByConsentID")
	}

	var r0 []consentmodel.ConsentStatusAudit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.ConsentStatusAudit, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.ConsentStatusAudit); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentStatusAudit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetStatusAuditByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusAuditByConsentID'
type ConsentStore_GetStatusAuditByConsentID_Call struct {
	*mock.Call
}

// GetStatusAuditByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetStatusAuditByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetStatusAuditByConsentID_Call {
	return &ConsentStore_GetStatusAuditByConsentID_Call{Call: _e.mock.On("GetStatusAuditByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetStatusAuditByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetStatusAuditByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetStatusAuditByConsentID_Call) Return(_a0 []consentmodel.ConsentStatusAudit, _a1 error) *ConsentStore_GetStatusAuditByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetStatusAuditByConsentID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.ConsentStatusAudit, error)) *ConsentStore_GetStatusAuditByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID, limit, offset
func (_m *ConsentStore) List(ctx context.Context, orgID string, limit int, offset int) ([]consentmodel.Consent, int, error) {
	ret := _m.Called(ctx, orgID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []consentmodel.Consent
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]consentmodel.Consent, int, error)); ok {
		return rf(ctx, orgID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []consentmodel.Consent); ok {
		r0 = rf(ctx, orgID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.Consent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, orgID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, orgID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ConsentStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ConsentStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - limit int
//   - offset int
func (_e *ConsentStore_Expecter) List(ctx interface{}, orgID interface{}, limit interface{}, offset interface{}) *ConsentStore_List_Call {
	return &ConsentStore_List_Call{Call: _e.mock.On("List", ctx, orgID, limit, offset)}
}

func (_c *ConsentStore_List_Call) Run(run func(ctx context.Context, orgID string, limit int, offset int)) *ConsentStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ConsentStore_List_Call) Return(_a0 []consentmodel.Consent, _a1 int, _a2 error) *ConsentStore_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ConsentStore_List_Call) RunAndReturn(run func(context.Context, string, int, int) ([]consentmodel.Consent, int, error)) *ConsentStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, filters
func (_m *ConsentStore) Search(ctx context.Context, filters consentmodel.ConsentSearchFilters) ([]consentmodel.Consent, int, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []consentmodel.Consent
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, consentmodel.ConsentSearchFilters) ([]consentmodel.Consent, int, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, consentmodel.ConsentSearchFilters) []consentmodel.Consent); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.Consent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, consentmodel.ConsentSearchFilters) int); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, consentmodel.ConsentSearchFilters) error); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ConsentStore_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type ConsentStore_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - filters consentmodel.ConsentSearchFilters
func (_e *ConsentStore_Expecter) Search(ctx interface{}, filters interface{}) *ConsentStore_Search_Call {
	return &ConsentStore_Search_Call{Call: _e.mock.On("Search", ctx, filters)}
}

func (_c *ConsentStore_Search_Call) Run(run func(ctx context.Context, filters consentmodel.ConsentSearchFilters)) *ConsentStore_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(consentmodel.ConsentSearchFilters))
	})
	return _c
}

func (_c *ConsentStore_Search_Call) Return(_a0 []consentmodel.Consent, _a1 int, _a2 error) *ConsentStore_Search_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ConsentStore_Search_Call) RunAndReturn(run func(context.Context, consentmodel.ConsentSearchFilters) ([]consentmodel.Consent, int, error)) *ConsentStore_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: tx, consent
func (_m *ConsentStore) Update(tx model.TxInterface, consent *consentmodel.Consent) error {
	ret := _m.Called(tx, consent)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.Consent) error); ok {
		r0 = rf(tx, consent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ConsentStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consent *consentmodel.Consent
func (_e *ConsentStore_Expecter) Update(tx interface{}, consent interface{}) *ConsentStore_Update_Call {
	return &ConsentStore_Update_Call{Call: _e.mock.On("Update", tx, consent)}
}

func (_c *ConsentStore_Update_Call) Run(run func(tx model.TxInterface, consent *consentmodel.Consent)) *ConsentStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.Consent))
	})
	return _c
}

func (_c *ConsentStore_Update_Call) Return(_a0 error) *ConsentStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_Update_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.Consent) error) *ConsentStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: tx, consentID, orgID, status, updatedTime
func (_m *ConsentStore) UpdateStatus(tx model.TxInterface, consentID string, orgID string, status string, updatedTime int64) error {
	ret := _m.Called(tx, consentID, orgID, status, updatedTime)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string, string, int64) error); ok {
		r0 = rf(tx, consentID, orgID, status, updatedTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type ConsentStore_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
//   - status string
//   - updatedTime int64
func (_e *ConsentStore_Expecter) UpdateStatus(tx interface{}, consentID interface{}, orgID interface{}, status interface{}, updatedTime interface{}) *ConsentStore_UpdateStatus_Call {
	return &ConsentStore_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", tx, consentID, orgID, status, updatedTime)}
}

func (_c *ConsentStore_UpdateStatus_Call) Run(run func(tx model.TxInterface, consentID string, orgID string, status string, updatedTime int64)) *ConsentStore_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string), args[3].(string), args[4].(int64))
	})
	return _c
}

func (_c *ConsentStore_UpdateStatus_Call) Return(_a0 error) *ConsentStore_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_UpdateStatus_Call) RunAndReturn(run func(model.TxInterface, string, string, string, int64) error) *ConsentStore_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsentStore creates a new instance of ConsentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentStore {
	mock := &ConsentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
