// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfacesmock

import (
	context "context"

	consentpurposemodel "github.com/wso2/openfgc/internal/consentpurpose/model"

	mock "github.com/stretchr/testify/mock"

	model "github.com/wso2/openfgc/internal/system/database/model"
)

// ConsentPurposeStore is an autogenerated mock type for the ConsentPurposeStore type
type ConsentPurposeStore struct {
	mock.Mock
}

// CheckPurposeNameExists provides a mock function with given fields: ctx, name, clientID, orgID, excludePurposeID
func (_m *ConsentPurposeStore) CheckPurposeNameExists(ctx context.Context, name string, clientID string, orgID string, excludePurposeID *string) (bool, error) {
	ret := _m.Called(ctx, name, clientID, orgID, excludePurposeID)

	if len(ret) == 0 {
		panic("no return value specified for CheckPurposeNameExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) (bool, error)); ok {
		return rf(ctx, name, clientID, orgID, excludePurposeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) bool); ok {
		r0 = rf(ctx, name, clientID, orgID, excludePurposeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *string) error); ok {
		r1 = rf(ctx, name, clientID, orgID, excludePurposeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePurpose provides a mock function with given fields: tx, purpose
func (_m *ConsentPurposeStore) CreatePurpose(tx model.TxInterface, purpose *consentpurposemodel.ConsentPurpose) error {
	ret := _m.Called(tx, purpose)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurpose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentpurposemodel.ConsentPurpose) error); ok {
		r0 = rf(tx, purpose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePurpose provides a mock function with given fields: tx, purposeID, orgID
func (_m *ConsentPurposeStore) DeletePurpose(tx model.TxInterface, purposeID string, orgID string) error {
	ret := _m.Called(tx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurpose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, purposeID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePurposeElements provides a mock function with given fields: tx, purposeID, orgID
func (_m *ConsentPurposeStore) DeletePurposeElements(tx model.TxInterface, purposeID string, orgID string) error {
	ret := _m.Called(tx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurposeElements")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, purposeID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPurposeByID provides a mock function with given fields: ctx, purposeID, orgID
func (_m *ConsentPurposeStore) GetPurposeByID(ctx context.Context, purposeID string, orgID string) (*consentpurposemodel.ConsentPurpose, error) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposeByID")
	}

	var r0 *consentpurposemodel.ConsentPurpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*consentpurposemodel.ConsentPurpose, error)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *consentpurposemodel.ConsentPurpose); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentpurposemodel.ConsentPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPurposeElements provides a mock function with given fields: ctx, purposeID, orgID
func (_m *ConsentPurposeStore) GetPurposeElements(ctx context.Context, purposeID string, orgID string) ([]consentpurposemodel.PurposeElement, error) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposeElements")
	}

	var r0 []consentpurposemodel.PurposeElement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentpurposemodel.PurposeElement, error)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentpurposemodel.PurposeElement); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentpurposemodel.PurposeElement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsElementUsedInPurposes provides a mock function with given fields: ctx, elementID, orgID
func (_m *ConsentPurposeStore) IsElementUsedInPurposes(ctx context.Context, elementID string, orgID string) (bool, error) {
	ret := _m.Called(ctx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for IsElementUsedInPurposes")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, elementID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, elementID, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, elementID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkElementToPurpose provides a mock function with given fields: tx, purposeID, elementID, orgID, isMandatory
func (_m *ConsentPurposeStore) LinkElementToPurpose(tx model.TxInterface, purposeID string, elementID string, orgID string, isMandatory bool) error {
	ret := _m.Called(tx, purposeID, elementID, orgID, isMandatory)

	if len(ret) == 0 {
		panic("no return value specified for LinkElementToPurpose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string, string, bool) error); ok {
		r0 = rf(tx, purposeID, elementID, orgID, isMandatory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListPurposes provides a mock function with given fields: ctx, orgID, name, clientIDs, elementNames, offset, limit
func (_m *ConsentPurposeStore) ListPurposes(ctx context.Context, orgID string, name string, clientIDs []string, elementNames []string, offset int, limit int) ([]consentpurposemodel.ConsentPurpose, int, error) {
	ret := _m.Called(ctx, orgID, name, clientIDs, elementNames, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPurposes")
	}

	var r0 []consentpurposemodel.ConsentPurpose
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string, []string, int, int) ([]consentpurposemodel.ConsentPurpose, int, error)); ok {
		return rf(ctx, orgID, name, clientIDs, elementNames, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string, []string, int, int) []consentpurposemodel.ConsentPurpose); ok {
		r0 = rf(ctx, orgID, name, clientIDs, elementNames, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentpurposemodel.ConsentPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string, []string, int, int) int); ok {
		r1 = rf(ctx, orgID, name, clientIDs, elementNames, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, []string, []string, int, int) error); ok {
		r2 = rf(ctx, orgID, name, clientIDs, elementNames, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdatePurpose provides a mock function with given fields: tx, purpose
func (_m *ConsentPurposeStore) UpdatePurpose(tx model.TxInterface, purpose *consentpurposemodel.ConsentPurpose) error {
	ret := _m.Called(tx, purpose)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePurpose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentpurposemodel.ConsentPurpose) error); ok {
		r0 = rf(tx, purpose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsentPurposeStore creates a new instance of ConsentPurposeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentPurposeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentPurposeStore {
	mock := &ConsentPurposeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
