// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfacesmock

import (
	context "context"

	consentelementmodel "github.com/wso2/openfgc/internal/consentelement/model"

	mock "github.com/stretchr/testify/mock"

	model "github.com/wso2/openfgc/internal/system/database/model"
)

// ConsentElementStore is an autogenerated mock type for the ConsentElementStore type
type ConsentElementStore struct {
	mock.Mock
}

type ConsentElementStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsentElementStore) EXPECT() *ConsentElementStore_Expecter {
	return &ConsentElementStore_Expecter{mock: &_m.Mock}
}

// CheckNameExists provides a mock function with given fields: ctx, name, orgID
func (_m *ConsentElementStore) CheckNameExists(ctx context.Context, name string, orgID string) (bool, error) {
	ret := _m.Called(ctx, name, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CheckNameExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, name, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, name, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentElementStore_CheckNameExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckNameExists'
type ConsentElementStore_CheckNameExists_Call struct {
	*mock.Call
}

// CheckNameExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - orgID string
func (_e *ConsentElementStore_Expecter) CheckNameExists(ctx interface{}, name interface{}, orgID interface{}) *ConsentElementStore_CheckNameExists_Call {
	return &ConsentElementStore_CheckNameExists_Call{Call: _e.mock.On("CheckNameExists", ctx, name, orgID)}
}

func (_c *ConsentElementStore_CheckNameExists_Call) Run(run func(ctx context.Context, name string, orgID string)) *ConsentElementStore_CheckNameExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentElementStore_CheckNameExists_Call) Return(_a0 bool, _a1 error) *ConsentElementStore_CheckNameExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentElementStore_CheckNameExists_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *ConsentElementStore_CheckNameExists_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: tx, element
func (_m *ConsentElementStore) Create(tx model.TxInterface, element *consentelementmodel.ConsentElement) error {
	ret := _m.Called(tx, element)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentelementmodel.ConsentElement) error); ok {
		r0 = rf(tx, element)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentElementStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ConsentElementStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx model.TxInterface
//   - element *consentelementmodel.ConsentElement
func (_e *ConsentElementStore_Expecter) Create(tx interface{}, element interface{}) *ConsentElementStore_Create_Call {
	return &ConsentElementStore_Create_Call{Call: _e.mock.On("Create", tx, element)}
}

func (_c *ConsentElementStore_Create_Call) Run(run func(tx model.TxInterface, element *consentelementmodel.ConsentElement)) *ConsentElementStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentelementmodel.ConsentElement))
	})
	return _c
}

func (_c *ConsentElementStore_Create_Call) Return(_a0 error) *ConsentElementStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentElementStore_Create_Call) RunAndReturn(run func(model.TxInterface, *consentelementmodel.ConsentElement) error) *ConsentElementStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProperties provides a mock function with given fields: tx, properties
func (_m *ConsentElementStore) CreateProperties(tx model.TxInterface, properties []consentelementmodel.ConsentElementProperty) error {
	ret := _m.Called(tx, properties)

	if len(ret) == 0 {
		panic("no return value specified for CreateProperties")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, []consentelementmodel.ConsentElementProperty) error); ok {
		r0 = rf(tx, properties)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentElementStore_CreateProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProperties'
type ConsentElementStore_CreateProperties_Call struct {
	*mock.Call
}

// CreateProperties is a helper method to define mock.On call
//   - tx model.TxInterface
//   - properties []consentelementmodel.ConsentElementProperty
func (_e *ConsentElementStore_Expecter) CreateProperties(tx interface{}, properties interface{}) *ConsentElementStore_CreateProperties_Call {
	return &ConsentElementStore_CreateProperties_Call{Call: _e.mock.On("CreateProperties", tx, properties)}
}

func (_c *ConsentElementStore_CreateProperties_Call) Run(run func(tx model.TxInterface, properties []consentelementmodel.ConsentElementProperty)) *ConsentElementStore_CreateProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].([]consentelementmodel.ConsentElementProperty))
	})
	return _c
}

func (_c *ConsentElementStore_CreateProperties_Call) Return(_a0 error) *ConsentElementStore_CreateProperties_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentElementStore_CreateProperties_Call) RunAndReturn(run func(model.TxInterface, []consentelementmodel.ConsentElementProperty) error) *ConsentElementStore_CreateProperties_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: tx, elementID, orgID
func (_m *ConsentElementStore) Delete(tx model.TxInterface, elementID string, orgID string) error {
	ret := _m.Called(tx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, elementID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentElementStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ConsentElementStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - tx model.TxInterface
//   - elementID string
//   - orgID string
func (_e *ConsentElementStore_Expecter) Delete(tx interface{}, elementID interface{}, orgID interface{}) *ConsentElementStore_Delete_Call {
	return &ConsentElementStore_Delete_Call{Call: _e.mock.On("Delete", tx, elementID, orgID)}
}

func (_c *ConsentElementStore_Delete_Call) Run(run func(tx model.TxInterface, elementID string, orgID string)) *ConsentElementStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentElementStore_Delete_Call) Return(_a0 error) *ConsentElementStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentElementStore_Delete_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentElementStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePropertiesByElementID provides a mock function with given fields: tx, elementID, orgID
func (_m *ConsentElementStore) DeletePropertiesByElementID(tx model.TxInterface, elementID string, orgID string) error {
	ret := _m.Called(tx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePropertiesByElementID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, elementID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentElementStore_DeletePropertiesByElementID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePropertiesByElementID'
type ConsentElementStore_DeletePropertiesByElementID_Call struct {
	*mock.Call
}

// DeletePropertiesByElementID is a helper method to define mock.On call
//   - tx model.TxInterface
//   - elementID string
//   - orgID string
func (_e *ConsentElementStore_Expecter) DeletePropertiesByElementID(tx interface{}, elementID interface{}, orgID interface{}) *ConsentElementStore_DeletePropertiesByElementID_Call {
	return &ConsentElementStore_DeletePropertiesByElementID_Call{Call: _e.mock.On("DeletePropertiesByElementID", tx, elementID, orgID)}
}

func (_c *ConsentElementStore_DeletePropertiesByElementID_Call) Run(run func(tx model.TxInterface, elementID string, orgID string)) *ConsentElementStore_DeletePropertiesByElementID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentElementStore_DeletePropertiesByElementID_Call) Return(_a0 error) *ConsentElementStore_DeletePropertiesByElementID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentElementStore_DeletePropertiesByElementID_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentElementStore_DeletePropertiesByElementID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, purposeID, orgID
func (_m *ConsentElementStore) GetByID(ctx context.Context, purposeID string, orgID string) (*consentelementmodel.ConsentElement, error) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *consentelementmodel.ConsentElement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*consentelementmodel.ConsentElement, error)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *consentelementmodel.ConsentElement); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentelementmodel.ConsentElement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentElementStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ConsentElementStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - purposeID string
//   - orgID string
func (_e *ConsentElementStore_Expecter) GetByID(ctx interface{}, purposeID interface{}, orgID interface{}) *ConsentElementStore_GetByID_Call {
	return &ConsentElementStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, purposeID, orgID)}
}

func (_c *ConsentElementStore_GetByID_Call) Run(run func(ctx context.Context, purposeID string, orgID string)) *ConsentElementStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentElementStore_GetByID_Call) Return(_a0 *consentelementmodel.ConsentElement, _a1 error) *ConsentElementStore_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentElementStore_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*consentelementmodel.ConsentElement, error)) *ConsentElementStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name, orgID
func (_m *ConsentElementStore) GetByName(ctx context.Context, name string, orgID string) (*consentelementmodel.ConsentElement, error) {
	ret := _m.Called(ctx, name, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *consentelementmodel.ConsentElement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*consentelementmodel.ConsentElement, error)); ok {
		return rf(ctx, name, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *consentelementmodel.ConsentElement); ok {
		r0 = rf(ctx, name, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentelementmodel.ConsentElement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentElementStore_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type ConsentElementStore_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - orgID string
func (_e *ConsentElementStore_Expecter) GetByName(ctx interface{}, name interface{}, orgID interface{}) *ConsentElementStore_GetByName_Call {
	return &ConsentElementStore_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name, orgID)}
}

func (_c *ConsentElementStore_GetByName_Call) Run(run func(ctx context.Context, name string, orgID string)) *ConsentElementStore_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentElementStore_GetByName_Call) Return(_a0 *consentelementmodel.ConsentElement, _a1 error) *ConsentElementStore_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentElementStore_GetByName_Call) RunAndReturn(run func(context.Context, string, string) (*consentelementmodel.ConsentElement, error)) *ConsentElementStore_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetIDsByNames provides a mock function with given fields: ctx, names, orgID
func (_m *ConsentElementStore) GetIDsByNames(ctx context.Context, names []string, orgID string) (map[string]string, error) {
	ret := _m.Called(ctx, names, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetIDsByNames")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) (map[string]string, error)); ok {
		return rf(ctx, names, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) map[string]string); ok {
		r0 = rf(ctx, names, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, names, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentElementStore_GetIDsByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIDsByNames'
type ConsentElementStore_GetIDsByNames_Call struct {
	*mock.Call
}

// GetIDsByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - names []string
//   - orgID string
func (_e *ConsentElementStore_Expecter) GetIDsByNames(ctx interface{}, names interface{}, orgID interface{}) *ConsentElementStore_GetIDsByNames_Call {
	return &ConsentElementStore_GetIDsByNames_Call{Call: _e.mock.On("GetIDsByNames", ctx, names, orgID)}
}

func (_c *ConsentElementStore_GetIDsByNames_Call) Run(run func(ctx context.Context, names []string, orgID string)) *ConsentElementStore_GetIDsByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string))
	})
	return _c
}

func (_c *ConsentElementStore_GetIDsByNames_Call) Return(_a0 map[string]string, _a1 error) *ConsentElementStore_GetIDsByNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentElementStore_GetIDsByNames_Call) RunAndReturn(run func(context.Context, []string, string) (map[string]string, error)) *ConsentElementStore_GetIDsByNames_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertiesByElementID provides a mock function with given fields: ctx, elementID, orgID
func (_m *ConsentElementStore) GetPropertiesByElementID(ctx context.Context, elementID string, orgID string) ([]consentelementmodel.ConsentElementProperty, error) {
	ret := _m.Called(ctx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPropertiesByElementID")
	}

	var r0 []consentelementmodel.ConsentElementProperty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentelementmodel.ConsentElementProperty, error)); ok {
		return rf(ctx, elementID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentelementmodel.ConsentElementProperty); ok {
		r0 = rf(ctx, elementID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentelementmodel.ConsentElementProperty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, elementID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentElementStore_GetPropertiesByElementID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertiesByElementID'
type ConsentElementStore_GetPropertiesByElementID_Call struct {
	*mock.Call
}

// GetPropertiesByElementID is a helper method to define mock.On call
//   - ctx context.Context
//   - elementID string
//   - orgID string
func (_e *ConsentElementStore_Expecter) GetPropertiesByElementID(ctx interface{}, elementID interface{}, orgID interface{}) *ConsentElementStore_GetPropertiesByElementID_Call {
	return &ConsentElementStore_GetPropertiesByElementID_Call{Call: _e.mock.On("GetPropertiesByElementID", ctx, elementID, orgID)}
}

func (_c *ConsentElementStore_GetPropertiesByElementID_Call) Run(run func(ctx context.Context, elementID string, orgID string)) *ConsentElementStore_GetPropertiesByElementID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentElementStore_GetPropertiesByElementID_Call) Return(_a0 []consentelementmodel.ConsentElementProperty, _a1 error) *ConsentElementStore_GetPropertiesByElementID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentElementStore_GetPropertiesByElementID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentelementmodel.ConsentElementProperty, error)) *ConsentElementStore_GetPropertiesByElementID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID, limit, offset, name
func (_m *ConsentElementStore) List(ctx context.Context, orgID string, limit int, offset int, name string) ([]consentelementmodel.ConsentElement, int, error) {
	ret := _m.Called(ctx, orgID, limit, offset, name)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []consentelementmodel.ConsentElement
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) ([]consentelementmodel.ConsentElement, int, error)); ok {
		return rf(ctx, orgID, limit, offset, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) []consentelementmodel.ConsentElement); ok {
		r0 = rf(ctx, orgID, limit, offset, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentelementmodel.ConsentElement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, string) int); ok {
		r1 = rf(ctx, orgID, limit, offset, name)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, string) error); ok {
		r2 = rf(ctx, orgID, limit, offset, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ConsentElementStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ConsentElementStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - limit int
//   - offset int
//   - name string
func (_e *ConsentElementStore_Expecter) List(ctx interface{}, orgID interface{}, limit interface{}, offset interface{}, name interface{}) *ConsentElementStore_List_Call {
	return &ConsentElementStore_List_Call{Call: _e.mock.On("List", ctx, orgID, limit, offset, name)}
}

func (_c *ConsentElementStore_List_Call) Run(run func(ctx context.Context, orgID string, limit int, offset int, name string)) *ConsentElementStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *ConsentElementStore_List_Call) Return(_a0 []consentelementmodel.ConsentElement, _a1 int, _a2 error) *ConsentElementStore_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ConsentElementStore_List_Call) RunAndReturn(run func(context.Context, string, int, int, string) ([]consentelementmodel.ConsentElement, int, error)) *ConsentElementStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: tx, element
func (_m *ConsentElementStore) Update(tx model.TxInterface, element *consentelementmodel.ConsentElement) error {
	ret := _m.Called(tx, element)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentelementmodel.ConsentElement) error); ok {
		r0 = rf(tx, element)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentElementStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ConsentElementStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx model.TxInterface
//   - element *consentelementmodel.ConsentElement
func (_e *ConsentElementStore_Expecter) Update(tx interface{}, element interface{}) *ConsentElementStore_Update_Call {
	return &ConsentElementStore_Update_Call{Call: _e.mock.On("Update", tx, element)}
}

func (_c *ConsentElementStore_Update_Call) Run(run func(tx model.TxInterface, element *consentelementmodel.ConsentElement)) *ConsentElementStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentelementmodel.ConsentElement))
	})
	return _c
}

func (_c *ConsentElementStore_Update_Call) Return(_a0 error) *ConsentElementStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentElementStore_Update_Call) RunAndReturn(run func(model.TxInterface, *consentelementmodel.ConsentElement) error) *ConsentElementStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsentElementStore creates a new instance of ConsentElementStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentElementStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentElementStore {
	mock := &ConsentElementStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
