// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfacesmock

import (
	context "context"

	consentmodel "github.com/wso2/openfgc/internal/consent/model"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wso2/openfgc/internal/system/database/model"
)

// ConsentStore is an autogenerated mock type for the ConsentStore type
type ConsentStore struct {
	mock.Mock
}

type ConsentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsentStore) EXPECT() *ConsentStore_Expecter {
	return &ConsentStore_Expecter{mock: &_m.Mock}
}

// CheckPurposeUsedInConsents provides a mock function with given fields: ctx, purposeID, orgID
func (_m *ConsentStore) CheckPurposeUsedInConsents(ctx context.Context, purposeID string, orgID string) (bool, error) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CheckPurposeUsedInConsents")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_CheckPurposeUsedInConsents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPurposeUsedInConsents'
type ConsentStore_CheckPurposeUsedInConsents_Call struct {
	*mock.Call
}

// CheckPurposeUsedInConsents is a helper method to define mock.On call
//   - ctx context.Context
//   - purposeID string
//   - orgID string
func (_e *ConsentStore_Expecter) CheckPurposeUsedInConsents(ctx interface{}, purposeID interface{}, orgID interface{}) *ConsentStore_CheckPurposeUsedInConsents_Call {
	return &ConsentStore_CheckPurposeUsedInConsents_Call{Call: _e.mock.On("CheckPurposeUsedInConsents", ctx, purposeID, orgID)}
}

func (_c *ConsentStore_CheckPurposeUsedInConsents_Call) Run(run func(ctx context.Context, purposeID string, orgID string)) *ConsentStore_CheckPurposeUsedInConsents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_CheckPurposeUsedInConsents_Call) Return(_a0 bool, _a1 error) *ConsentStore_CheckPurposeUsedInConsents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_CheckPurposeUsedInConsents_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *ConsentStore_CheckPurposeUsedInConsents_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: tx, consent
func (_m *ConsentStore) Create(tx model.TxInterface, consent *consentmodel.Consent) error {
	ret := _m.Called(tx, consent)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.Consent) error); ok {
		r0 = rf(tx, consent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ConsentStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consent *consentmodel.Consent
func (_e *ConsentStore_Expecter) Create(tx interface{}, consent interface{}) *ConsentStore_Create_Call {
	return &ConsentStore_Create_Call{Call: _e.mock.On("Create", tx, consent)}
}

func (_c *ConsentStore_Create_Call) Run(run func(tx model.TxInterface, consent *consentmodel.Consent)) *ConsentStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.Consent))
	})
	return _c
}

func (_c *ConsentStore_Create_Call) Return(_a0 error) *ConsentStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_Create_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.Consent) error) *ConsentStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAttributes provides a mock function with given fields: tx, attributes
func (_m *ConsentStore) CreateAttributes(tx model.TxInterface, attributes []consentmodel.ConsentAttribute) error {
	ret := _m.Called(tx, attributes)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttributes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, []consentmodel.ConsentAttribute) error); ok {
		r0 = rf(tx, attributes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreateAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAttributes'
type ConsentStore_CreateAttributes_Call struct {
	*mock.Call
}

// CreateAttributes is a helper method to define mock.On call
//   - tx model.TxInterface
//   - attributes []consentmodel.ConsentAttribute
func (_e *ConsentStore_Expecter) CreateAttributes(tx interface{}, attributes interface{}) *ConsentStore_CreateAttributes_Call {
	return &ConsentStore_CreateAttributes_Call{Call: _e.mock.On("CreateAttributes", tx, attributes)}
}

func (_c *ConsentStore_CreateAttributes_Call) Run(run func(tx model.TxInterface, attributes []consentmodel.ConsentAttribute)) *ConsentStore_CreateAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].([]consentmodel.ConsentAttribute))
	})
	return _c
}

func (_c *ConsentStore_CreateAttributes_Call) Return(_a0 error) *ConsentStore_CreateAttributes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreateAttributes_Call) RunAndReturn(run func(model.TxInterface, []consentmodel.ConsentAttribute) error) *ConsentStore_CreateAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// CreateConsentPurposeMapping provides a mock function with given fields: tx, consentID, purposeID, orgID
func (_m *ConsentStore) CreateConsentPurposeMapping(tx model.TxInterface, consentID string, purposeID string, orgID string) error {
	ret := _m.Called(tx, consentID, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CreateConsentPurposeMapping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string, string) error); ok {
		r0 = rf(tx, consentID, purposeID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreateConsentPurposeMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConsentPurposeMapping'
type ConsentStore_CreateConsentPurposeMapping_Call struct {
	*mock.Call
}

// CreateConsentPurposeMapping is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - purposeID string
//   - orgID string
func (_e *ConsentStore_Expecter) CreateConsentPurposeMapping(tx interface{}, consentID interface{}, purposeID interface{}, orgID interface{}) *ConsentStore_CreateConsentPurposeMapping_Call {
	return &ConsentStore_CreateConsentPurposeMapping_Call{Call: _e.mock.On("CreateConsentPurposeMapping", tx, consentID, purposeID, orgID)}
}

func (_c *ConsentStore_CreateConsentPurposeMapping_Call) Run(run func(tx model.TxInterface, consentID string, purposeID string, orgID string)) *ConsentStore_CreateConsentPurposeMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ConsentStore_CreateConsentPurposeMapping_Call) Return(_a0 error) *ConsentStore_CreateConsentPurposeMapping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreateConsentPurposeMapping_Call) RunAndReturn(run func(model.TxInterface, string, string, string) error) *ConsentStore_CreateConsentPurposeMapping_Call {
	_c.Call.Return(run)
	return _c
}

// CreateHistory provides a mock function with given fields: tx, history
func (_m *ConsentStore) CreateHistory(tx model.TxInterface, history *consentmodel.ConsentHistory) error {
	ret := _m.Called(tx, history)

	if len(ret) == 0 {
		panic("no return value specified for CreateHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.ConsentHistory) error); ok {
		r0 = rf(tx, history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreateHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHistory'
type ConsentStore_CreateHistory_Call struct {
	*mock.Call
}

// CreateHistory is a helper method to define mock.On call
//   - tx model.TxInterface
//   - history *consentmodel.ConsentHistory
func (_e *ConsentStore_Expecter) CreateHistory(tx interface{}, history interface{}) *ConsentStore_CreateHistory_Call {
	return &ConsentStore_CreateHistory_Call{Call: _e.mock.On("CreateHistory", tx, history)}
}

func (_c *ConsentStore_CreateHistory_Call) Run(run func(tx model.TxInterface, history *consentmodel.ConsentHistory)) *ConsentStore_CreateHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.ConsentHistory))
	})
	return _c
}

func (_c *ConsentStore_CreateHistory_Call) Return(_a0 error) *ConsentStore_CreateHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreateHistory_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.ConsentHistory) error) *ConsentStore_CreateHistory_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePurposeElementApproval provides a mock function with given fields: tx, approval
func (_m *ConsentStore) CreatePurposeElementApproval(tx model.TxInterface, approval *consentmodel.ConsentElementApprovalRecord) error {
	ret := _m.Called(tx, approval)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurposeElementApproval")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.ConsentElementApprovalRecord) error); ok {
		r0 = rf(tx, approval)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreatePurposeElementApproval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePurposeElementApproval'
type ConsentStore_CreatePurposeElementApproval_Call struct {
	*mock.Call
}

// CreatePurposeElementApproval is a helper method to define mock.On call
//   - tx model.TxInterface
//   - approval *consentmodel.ConsentElementApprovalRecord
func (_e *ConsentStore_Expecter) CreatePurposeElementApproval(tx interface{}, approval interface{}) *ConsentStore_CreatePurposeElementApproval_Call {
	return &ConsentStore_CreatePurposeElementApproval_Call{Call: _e.mock.On("CreatePurposeElementApproval", tx, approval)}
}

func (_c *ConsentStore_CreatePurposeElementApproval_Call) Run(run func(tx model.TxInterface, approval *consentmodel.ConsentElementApprovalRecord)) *ConsentStore_CreatePurposeElementApproval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.ConsentElementApprovalRecord))
	})
	return _c
}

func (_c *ConsentStore_CreatePurposeElementApproval_Call) Return(_a0 error) *ConsentStore_CreatePurposeElementApproval_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreatePurposeElementApproval_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.ConsentElementApprovalRecord) error) *ConsentStore_CreatePurposeElementApproval_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStatusAudit provides a mock function with given fields: tx, audit
func (_m *ConsentStore) CreateStatusAudit(tx model.TxInterface, audit *consentmodel.ConsentStatusAudit) error {
	ret := _m.Called(tx, audit)

	if len(ret) == 0 {
		panic("no return value specified for CreateStatusAudit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.ConsentStatusAudit) error); ok {
		r0 = rf(tx, audit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreateStatusAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStatusAudit'
type ConsentStore_CreateStatusAudit_Call struct {
	*mock.Call
}

// CreateStatusAudit is a helper method to define mock.On call
//   - tx model.TxInterface
//   - audit *consentmodel.ConsentStatusAudit
func (_e *ConsentStore_Expecter) CreateStatusAudit(tx interface{}, audit interface{}) *ConsentStore_CreateStatusAudit_Call {
	return &ConsentStore_CreateStatusAudit_Call{Call: _e.mock.On("CreateStatusAudit", tx, audit)}
}

func (_c *ConsentStore_CreateStatusAudit_Call) Run(run func(tx model.TxInterface, audit *consentmodel.ConsentStatusAudit)) *ConsentStore_CreateStatusAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.ConsentStatusAudit))
	})
	return _c
}

func (_c *ConsentStore_CreateStatusAudit_Call) Return(_a0 error) *ConsentStore_CreateStatusAudit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreateStatusAudit_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.ConsentStatusAudit) error) *ConsentStore_CreateStatusAudit_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttributesByConsentID provides a mock function with given fields: tx, consentID, orgID
func (_m *ConsentStore) DeleteAttributesByConsentID(tx model.TxInterface, consentID string, orgID string) error {
	ret := _m.Called(tx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttributesByConsentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, consentID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_DeleteAttributesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttributesByConsentID'
type ConsentStore_DeleteAttributesByConsentID_Call struct {
	*mock.Call
}

// DeleteAttributesByConsentID is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) DeleteAttributesByConsentID(tx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_DeleteAttributesByConsentID_Call {
	return &ConsentStore_DeleteAttributesByConsentID_Call{Call: _e.mock.On("DeleteAttributesByConsentID", tx, consentID, orgID)}
}

func (_c *ConsentStore_DeleteAttributesByConsentID_Call) Run(run func(tx model.TxInterface, consentID string, orgID string)) *ConsentStore_DeleteAttributesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_DeleteAttributesByConsentID_Call) Return(_a0 error) *ConsentStore_DeleteAttributesByConsentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_DeleteAttributesByConsentID_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentStore_DeleteAttributesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteConsentPurposeMappingsByConsentID provides a mock function with given fields: tx, consentID, orgID
func (_m *ConsentStore) DeleteConsentPurposeMappingsByConsentID(tx model.TxInterface, consentID string, orgID string) error {
	ret := _m.Called(tx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConsentPurposeMappingsByConsentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, consentID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_DeleteConsentPurposeMappingsByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConsentPurposeMappingsByConsentID'
type ConsentStore_DeleteConsentPurposeMappingsByConsentID_Call struct {
	*mock.Call
}

// DeleteConsentPurposeMappingsByConsentID is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) DeleteConsentPurposeMappingsByConsentID(tx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_DeleteConsentPurposeMappingsByConsentID_Call {
	return &ConsentStore_DeleteConsentPurposeMappingsByConsentID_Call{Call: _e.mock.On("DeleteConsentPurposeMappingsByConsentID", tx, consentID, orgID)}
}

func (_c *ConsentStore_DeleteConsentPurposeMappingsByConsentID_Call) Run(run func(tx model.TxInterface, consentID string, orgID string)) *ConsentStore_DeleteConsentPurposeMappingsByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_DeleteConsentPurposeMappingsByConsentID_Call) Return(_a0 error) *ConsentStore_DeleteConsentPurposeMappingsByConsentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_DeleteConsentPurposeMappingsByConsentID_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentStore_DeleteConsentPurposeMappingsByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePurposeElementApprovalsByConsentID provides a mock function with given fields: tx, consentID, orgID
func (_m *ConsentStore) DeletePurposeElementApprovalsByConsentID(tx model.TxInterface, consentID string, orgID string) error {
	ret := _m.Called(tx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurposeElementApprovalsByConsentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, consentID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_DeletePurposeElementApprovalsByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePurposeElementApprovalsByConsentID'
type ConsentStore_DeletePurposeElementApprovalsByConsentID_Call struct {
	*mock.Call
}

// DeletePurposeElementApprovalsByConsentID is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) DeletePurposeElementApprovalsByConsentID(tx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_DeletePurposeElementApprovalsByConsentID_Call {
	return &ConsentStore_DeletePurposeElementApprovalsByConsentID_Call{Call: _e.mock.On("DeletePurposeElementApprovalsByConsentID", tx, consentID, orgID)}
}

func (_c *ConsentStore_DeletePurposeElementApprovalsByConsentID_Call) Run(run func(tx model.TxInterface, consentID string, orgID string)) *ConsentStore_DeletePurposeElementApprovalsByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_DeletePurposeElementApprovalsByConsentID_Call) Return(_a0 error) *ConsentStore_DeletePurposeElementApprovalsByConsentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_DeletePurposeElementApprovalsByConsentID_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentStore_DeletePurposeElementApprovalsByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// FindConsentIDsByAttribute provides a mock function with given fields: ctx, key, value, orgID
func (_m *ConsentStore) FindConsentIDsByAttribute(ctx context.Context, key string, value string, orgID string) ([]string, error) {
	ret := _m.Called(ctx, key, value, orgID)

	if len(ret) == 0 {
		panic("no return value specified for FindConsentIDsByAttribute")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]string, error)); ok {
		return rf(ctx, key, value, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []string); ok {
		r0 = rf(ctx, key, value, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, key, value, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_FindConsentIDsByAttribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindConsentIDsByAttribute'
type ConsentStore_FindConsentIDsByAttribute_Call struct {
	*mock.Call
}

// FindConsentIDsByAttribute is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - orgID string
func (_e *ConsentStore_Expecter) FindConsentIDsByAttribute(ctx interface{}, key interface{}, value interface{}, orgID interface{}) *ConsentStore_FindConsentIDsByAttribute_Call {
	return &ConsentStore_FindConsentIDsByAttribute_Call{Call: _e.mock.On("FindConsentIDsByAttribute", ctx, key, value, orgID)}
}

func (_c *ConsentStore_FindConsentIDsByAttribute_Call) Run(run func(ctx context.Context, key string, value string, orgID string)) *ConsentStore_FindConsentIDsByAttribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ConsentStore_FindConsentIDsByAttribute_Call) Return(_a0 []string, _a1 error) *ConsentStore_FindConsentIDsByAttribute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_FindConsentIDsByAttribute_Call) RunAndReturn(run func(context.Context, string, string, string) ([]string, error)) *ConsentStore_FindConsentIDsByAttribute_Call {
	_c.Call.Return(run)
	return _c
}

// FindConsentIDsByAttributeKey provides a mock function with given fields: ctx, key, orgID
func (_m *ConsentStore) FindConsentIDsByAttributeKey(ctx context.Context, key string, orgID string) ([]string, error) {
	ret := _m.Called(ctx, key, orgID)

	if len(ret) == 0 {
		panic("no return value specified for FindConsentIDsByAttributeKey")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, key, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, key, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_FindConsentIDsByAttributeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindConsentIDsByAttributeKey'
type ConsentStore_FindConsentIDsByAttributeKey_Call struct {
	*mock.Call
}

// FindConsentIDsByAttributeKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - orgID string
func (_e *ConsentStore_Expecter) FindConsentIDsByAttributeKey(ctx interface{}, key interface{}, orgID interface{}) *ConsentStore_FindConsentIDsByAttributeKey_Call {
	return &ConsentStore_FindConsentIDsByAttributeKey_Call{Call: _e.mock.On("FindConsentIDsByAttributeKey", ctx, key, orgID)}
}

func (_c *ConsentStore_FindConsentIDsByAttributeKey_Call) Run(run func(ctx context.Context, key string, orgID string)) *ConsentStore_FindConsentIDsByAttributeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_FindConsentIDsByAttributeKey_Call) Return(_a0 []string, _a1 error) *ConsentStore_FindConsentIDsByAttributeKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_FindConsentIDsByAttributeKey_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *ConsentStore_FindConsentIDsByAttributeKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttributesByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetAttributesByConsentID(ctx context.Context, consentID string, orgID string) ([]consentmodel.ConsentAttribute, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttributesByConsentID")
	}

	var r0 []consentmodel.ConsentAttribute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.ConsentAttribute, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.ConsentAttribute); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentAttribute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetAttributesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttributesByConsentID'
type ConsentStore_GetAttributesByConsentID_Call struct {
	*mock.Call
}

// GetAttributesByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetAttributesByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetAttributesByConsentID_Call {
	return &ConsentStore_GetAttributesByConsentID_Call{Call: _e.mock.On("GetAttributesByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetAttributesByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetAttributesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentID_Call) Return(_a0 []consentmodel.ConsentAttribute, _a1 error) *ConsentStore_GetAttributesByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.ConsentAttribute, error)) *ConsentStore_GetAttributesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttributesByConsentIDs provides a mock function with given fields: ctx, consentIDs, orgID
func (_m *ConsentStore) GetAttributesByConsentIDs(ctx context.Context, consentIDs []string, orgID string) (map[string]map[string]string, error) {
	ret := _m.Called(ctx, consentIDs, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttributesByConsentIDs")
	}

	var r0 map[string]map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) (map[string]map[string]string, error)); ok {
		return rf(ctx, consentIDs, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) map[string]map[string]string); ok {
		r0 = rf(ctx, consentIDs, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, consentIDs, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetAttributesByConsentIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttributesByConsentIDs'
type ConsentStore_GetAttributesByConsentIDs_Call struct {
	*mock.Call
}

// GetAttributesByConsentIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - consentIDs []string
//   - orgID string
func (_e *ConsentStore_Expecter) GetAttributesByConsentIDs(ctx interface{}, consentIDs interface{}, orgID interface{}) *ConsentStore_GetAttributesByConsentIDs_Call {
	return &ConsentStore_GetAttributesByConsentIDs_Call{Call: _e.mock.On("GetAttributesByConsentIDs", ctx, consentIDs, orgID)}
}

func (_c *ConsentStore_GetAttributesByConsentIDs_Call) Run(run func(ctx context.Context, consentIDs []string, orgID string)) *ConsentStore_GetAttributesByConsentIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentIDs_Call) Return(_a0 map[string]map[string]string, _a1 error) *ConsentStore_GetAttributesByConsentIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentIDs_Call) RunAndReturn(run func(context.Context, []string, string) (map[string]map[string]string, error)) *ConsentStore_GetAttributesByConsentIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetByID(ctx context.Context, consentID string, orgID string) (*consentmodel.Consent, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *consentmodel.Consent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*consentmodel.Consent, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *consentmodel.Consent); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentmodel.Consent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ConsentStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetByID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetByID_Call {
	return &ConsentStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetByID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetByID_Call) Return(_a0 *consentmodel.Consent, _a1 error) *ConsentStore_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*consentmodel.Consent, error)) *ConsentStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDForUpdate provides a mock function with given fields: tx, consentID, orgID
func (_m *ConsentStore) GetByIDForUpdate(tx model.TxInterface, consentID string, orgID string) (*consentmodel.Consent, error) {
	ret := _m.Called(tx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDForUpdate")
	}

	var r0 *consentmodel.Consent
	var r1 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) (*consentmodel.Consent, error)); ok {
		return rf(tx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) *consentmodel.Consent); ok {
		r0 = rf(tx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentmodel.Consent)
		}
	}

	if rf, ok := ret.Get(1).(func(model.TxInterface, string, string) error); ok {
		r1 = rf(tx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDForUpdate'
type ConsentStore_GetByIDForUpdate_Call struct {
	*mock.Call
}

// GetByIDForUpdate is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetByIDForUpdate(tx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetByIDForUpdate_Call {
	return &ConsentStore_GetByIDForUpdate_Call{Call: _e.mock.On("GetByIDForUpdate", tx, consentID, orgID)}
}

func (_c *ConsentStore_GetByIDForUpdate_Call) Run(run func(tx model.TxInterface, consentID string, orgID string)) *ConsentStore_GetByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetByIDForUpdate_Call) Return(_a0 *consentmodel.Consent, _a1 error) *ConsentStore_GetByIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetByIDForUpdate_Call) RunAndReturn(run func(model.TxInterface, string, string) (*consentmodel.Consent, error)) *ConsentStore_GetByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetConsentPurposeMappingsByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetConsentPurposeMappingsByConsentID(ctx context.Context, consentID string, orgID string) ([]consentmodel.ConsentPurposeMapping, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetConsentPurposeMappingsByConsentID")
	}

	var r0 []consentmodel.ConsentPurposeMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.ConsentPurposeMapping, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.ConsentPurposeMapping); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentPurposeMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetConsentPurposeMappingsByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConsentPurposeMappingsByConsentID'
type ConsentStore_GetConsentPurposeMappingsByConsentID_Call struct {
	*mock.Call
}

// GetConsentPurposeMappingsByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetConsentPurposeMappingsByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetConsentPurposeMappingsByConsentID_Call {
	return &ConsentStore_GetConsentPurposeMappingsByConsentID_Call{Call: _e.mock.On("GetConsentPurposeMappingsByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetConsentPurposeMappingsByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetConsentPurposeMappingsByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetConsentPurposeMappingsByConsentID_Call) Return(_a0 []consentmodel.ConsentPurposeMapping, _a1 error) *ConsentStore_GetConsentPurposeMappingsByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetConsentPurposeMappingsByConsentID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.ConsentPurposeMapping, error)) *ConsentStore_GetConsentPurposeMappingsByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistoryByConsentID provides a mock function with given fields: ctx, consentID, orgID, includeSnapshots
func (_m *ConsentStore) GetHistoryByConsentID(ctx context.Context, consentID string, orgID string, includeSnapshots bool) ([]consentmodel.ConsentHistory, error) {
	ret := _m.Called(ctx, consentID, orgID, includeSnapshots)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryByConsentID")
	}

	var r0 []consentmodel.ConsentHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) ([]consentmodel.ConsentHistory, error)); ok {
		return rf(ctx, consentID, orgID, includeSnapshots)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) []consentmodel.ConsentHistory); ok {
		r0 = rf(ctx, consentID, orgID, includeSnapshots)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, consentID, orgID, includeSnapshots)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetHistoryByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoryByConsentID'
type ConsentStore_GetHistoryByConsentID_Call struct {
	*mock.Call
}

// GetHistoryByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
//   - includeSnapshots bool
func (_e *ConsentStore_Expecter) GetHistoryByConsentID(ctx interface{}, consentID interface{}, orgID interface{}, includeSnapshots interface{}) *ConsentStore_GetHistoryByConsentID_Call {
	return &ConsentStore_GetHistoryByConsentID_Call{Call: _e.mock.On("GetHistoryByConsentID", ctx, consentID, orgID, includeSnapshots)}
}

func (_c *ConsentStore_GetHistoryByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string, includeSnapshots bool)) *ConsentStore_GetHistoryByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *ConsentStore_GetHistoryByConsentID_Call) Return(_a0 []consentmodel.ConsentHistory, _a1 error) *ConsentStore_GetHistoryByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetHistoryByConsentID_Call) RunAndReturn(run func(context.Context, string, string, bool) ([]consentmodel.ConsentHistory, error)) *ConsentStore_GetHistoryByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPurposeElementApprovalsByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetPurposeElementApprovalsByConsentID(ctx context.Context, consentID string, orgID string) ([]consentmodel.ConsentElementApprovalRecord, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposeElementApprovalsByConsentID")
	}

	var r0 []consentmodel.ConsentElementApprovalRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.ConsentElementApprovalRecord, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.ConsentElementApprovalRecord); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentElementApprovalRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetPurposeElementApprovalsByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPurposeElementApprovalsByConsentID'
type ConsentStore_GetPurposeElementApprovalsByConsentID_Call struct {
	*mock.Call
}

// GetPurposeElementApprovalsByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetPurposeElementApprovalsByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetPurposeElementApprovalsByConsentID_Call {
	return &ConsentStore_GetPurposeElementApprovalsByConsentID_Call{Call: _e.mock.On("GetPurposeElementApprovalsByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetPurposeElementApprovalsByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetPurposeElementApprovalsByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetPurposeElementApprovalsByConsentID_Call) Return(_a0 []consentmodel.ConsentElementApprovalRecord, _a1 error) *ConsentStore_GetPurposeElementApprovalsByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetPurposeElementApprovalsByConsentID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.ConsentElementApprovalRecord, error)) *ConsentStore_GetPurposeElementApprovalsByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusAuditsByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetStatusAuditsByConsentID(ctx context.Context, consentID string, orgID string) ([]consentmodel.ConsentStatusAudit, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusAuditsByConsentID")
	}

	var r0 []consentmodel.ConsentStatusAudit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.ConsentStatusAudit, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.ConsentStatusAudit); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentStatusAudit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetStatusAuditsByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusAuditsByConsentID'
type ConsentStore_GetStatusAuditsByConsentID_Call struct {
	*mock.Call
}

// GetStatusAuditsByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetStatusAuditsByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetStatusAuditsByConsentID_Call {
	return &ConsentStore_GetStatusAuditsByConsentID_Call{Call: _e.mock.On("GetStatusAuditsByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetStatusAuditsByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetStatusAuditsByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetStatusAuditsByConsentID_Call) Return(_a0 []consentmodel.ConsentStatusAudit, _a1 error) *ConsentStore_GetStatusAuditsByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetStatusAuditsByConsentID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.ConsentStatusAudit, error)) *ConsentStore_GetStatusAuditsByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, filters
func (_m *ConsentStore) Search(ctx context.Context, filters consentmodel.ConsentSearchFilters) ([]consentmodel.Consent, int, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []consentmodel.Consent
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, consentmodel.ConsentSearchFilters) ([]consentmodel.Consent, int, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, consentmodel.ConsentSearchFilters) []consentmodel.Consent); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.Consent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, consentmodel.ConsentSearchFilters) int); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, consentmodel.ConsentSearchFilters) error); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ConsentStore_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type ConsentStore_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - filters consentmodel.ConsentSearchFilters
func (_e *ConsentStore_Expecter) Search(ctx interface{}, filters interface{}) *ConsentStore_Search_Call {
	return &ConsentStore_Search_Call{Call: _e.mock.On("Search", ctx, filters)}
}

func (_c *ConsentStore_Search_Call) Run(run func(ctx context.Context, filters consentmodel.ConsentSearchFilters)) *ConsentStore_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(consentmodel.ConsentSearchFilters))
	})
	return _c
}

func (_c *ConsentStore_Search_Call) Return(_a0 []consentmodel.Consent, _a1 int, _a2 error) *ConsentStore_Search_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ConsentStore_Search_Call) RunAndReturn(run func(context.Context, consentmodel.ConsentSearchFilters) ([]consentmodel.Consent, int, error)) *ConsentStore_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: tx, consent
func (_m *ConsentStore) Update(tx model.TxInterface, consent *consentmodel.Consent) error {
	ret := _m.Called(tx, consent)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.Consent) error); ok {
		r0 = rf(tx, consent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ConsentStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consent *consentmodel.Consent
func (_e *ConsentStore_Expecter) Update(tx interface{}, consent interface{}) *ConsentStore_Update_Call {
	return &ConsentStore_Update_Call{Call: _e.mock.On("Update", tx, consent)}
}

func (_c *ConsentStore_Update_Call) Run(run func(tx model.TxInterface, consent *consentmodel.Consent)) *ConsentStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.Consent))
	})
	return _c
}

func (_c *ConsentStore_Update_Call) Return(_a0 error) *ConsentStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_Update_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.Consent) error) *ConsentStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: tx, consentID, orgID, status, updatedTime
func (_m *ConsentStore) UpdateStatus(tx model.TxInterface, consentID string, orgID string, status string, updatedTime int64) error {
	ret := _m.Called(tx, consentID, orgID, status, updatedTime)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string, string, int64) error); ok {
		r0 = rf(tx, consentID, orgID, status, updatedTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type ConsentStore_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
//   - status string
//   - updatedTime int64
func (_e *ConsentStore_Expecter) UpdateStatus(tx interface{}, consentID interface{}, orgID interface{}, status interface{}, updatedTime interface{}) *ConsentStore_UpdateStatus_Call {
	return &ConsentStore_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", tx, consentID, orgID, status, updatedTime)}
}

func (_c *ConsentStore_UpdateStatus_Call) Run(run func(tx model.TxInterface, consentID string, orgID string, status string, updatedTime int64)) *ConsentStore_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string), args[3].(string), args[4].(int64))
	})
	return _c
}

func (_c *ConsentStore_UpdateStatus_Call) Return(_a0 error) *ConsentStore_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_UpdateStatus_Call) RunAndReturn(run func(model.TxInterface, string, string, string, int64) error) *ConsentStore_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsentStore creates a new instance of ConsentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentStore {
	mock := &ConsentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
