// Code generated by mockery v2.53.5. DO NOT EDIT.

package interfacesmock

import (
	context "context"

	consentmodel "github.com/wso2/openfgc/internal/consent/model"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wso2/openfgc/internal/system/database/model"
)

// ConsentStore is an autogenerated mock type for the ConsentStore type
type ConsentStore struct {
	mock.Mock
}

type ConsentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsentStore) EXPECT() *ConsentStore_Expecter {
	return &ConsentStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: tx, consent
func (_m *ConsentStore) Create(tx model.TxInterface, consent *consentmodel.Consent) error {
	ret := _m.Called(tx, consent)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.Consent) error); ok {
		r0 = rf(tx, consent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ConsentStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consent *consentmodel.Consent
func (_e *ConsentStore_Expecter) Create(tx interface{}, consent interface{}) *ConsentStore_Create_Call {
	return &ConsentStore_Create_Call{Call: _e.mock.On("Create", tx, consent)}
}

func (_c *ConsentStore_Create_Call) Run(run func(tx model.TxInterface, consent *consentmodel.Consent)) *ConsentStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.Consent))
	})
	return _c
}

func (_c *ConsentStore_Create_Call) Return(_a0 error) *ConsentStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_Create_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.Consent) error) *ConsentStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAttributes provides a mock function with given fields: tx, attributes
func (_m *ConsentStore) CreateAttributes(tx model.TxInterface, attributes []consentmodel.ConsentAttribute) error {
	ret := _m.Called(tx, attributes)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttributes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, []consentmodel.ConsentAttribute) error); ok {
		r0 = rf(tx, attributes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreateAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAttributes'
type ConsentStore_CreateAttributes_Call struct {
	*mock.Call
}

// CreateAttributes is a helper method to define mock.On call
//   - tx model.TxInterface
//   - attributes []consentmodel.ConsentAttribute
func (_e *ConsentStore_Expecter) CreateAttributes(tx interface{}, attributes interface{}) *ConsentStore_CreateAttributes_Call {
	return &ConsentStore_CreateAttributes_Call{Call: _e.mock.On("CreateAttributes", tx, attributes)}
}

func (_c *ConsentStore_CreateAttributes_Call) Run(run func(tx model.TxInterface, attributes []consentmodel.ConsentAttribute)) *ConsentStore_CreateAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].([]consentmodel.ConsentAttribute))
	})
	return _c
}

func (_c *ConsentStore_CreateAttributes_Call) Return(_a0 error) *ConsentStore_CreateAttributes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreateAttributes_Call) RunAndReturn(run func(model.TxInterface, []consentmodel.ConsentAttribute) error) *ConsentStore_CreateAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// CreateElementApproval provides a mock function with given fields: tx, approval
func (_m *ConsentStore) CreateElementApproval(tx model.TxInterface, approval *consentmodel.ConsentElementApproval) error {
	ret := _m.Called(tx, approval)

	if len(ret) == 0 {
		panic("no return value specified for CreateElementApproval")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.ConsentElementApproval) error); ok {
		r0 = rf(tx, approval)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreateElementApproval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateElementApproval'
type ConsentStore_CreateElementApproval_Call struct {
	*mock.Call
}

// CreateElementApproval is a helper method to define mock.On call
//   - tx model.TxInterface
//   - approval *consentmodel.ConsentElementApproval
func (_e *ConsentStore_Expecter) CreateElementApproval(tx interface{}, approval interface{}) *ConsentStore_CreateElementApproval_Call {
	return &ConsentStore_CreateElementApproval_Call{Call: _e.mock.On("CreateElementApproval", tx, approval)}
}

func (_c *ConsentStore_CreateElementApproval_Call) Run(run func(tx model.TxInterface, approval *consentmodel.ConsentElementApproval)) *ConsentStore_CreateElementApproval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.ConsentElementApproval))
	})
	return _c
}

func (_c *ConsentStore_CreateElementApproval_Call) Return(_a0 error) *ConsentStore_CreateElementApproval_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreateElementApproval_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.ConsentElementApproval) error) *ConsentStore_CreateElementApproval_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStatusAudit provides a mock function with given fields: tx, audit
func (_m *ConsentStore) CreateStatusAudit(tx model.TxInterface, audit *consentmodel.ConsentStatusAudit) error {
	ret := _m.Called(tx, audit)

	if len(ret) == 0 {
		panic("no return value specified for CreateStatusAudit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.ConsentStatusAudit) error); ok {
		r0 = rf(tx, audit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_CreateStatusAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStatusAudit'
type ConsentStore_CreateStatusAudit_Call struct {
	*mock.Call
}

// CreateStatusAudit is a helper method to define mock.On call
//   - tx model.TxInterface
//   - audit *consentmodel.ConsentStatusAudit
func (_e *ConsentStore_Expecter) CreateStatusAudit(tx interface{}, audit interface{}) *ConsentStore_CreateStatusAudit_Call {
	return &ConsentStore_CreateStatusAudit_Call{Call: _e.mock.On("CreateStatusAudit", tx, audit)}
}

func (_c *ConsentStore_CreateStatusAudit_Call) Run(run func(tx model.TxInterface, audit *consentmodel.ConsentStatusAudit)) *ConsentStore_CreateStatusAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.ConsentStatusAudit))
	})
	return _c
}

func (_c *ConsentStore_CreateStatusAudit_Call) Return(_a0 error) *ConsentStore_CreateStatusAudit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_CreateStatusAudit_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.ConsentStatusAudit) error) *ConsentStore_CreateStatusAudit_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttributesByConsentID provides a mock function with given fields: tx, consentID, orgID
func (_m *ConsentStore) DeleteAttributesByConsentID(tx model.TxInterface, consentID string, orgID string) error {
	ret := _m.Called(tx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttributesByConsentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, consentID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_DeleteAttributesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttributesByConsentID'
type ConsentStore_DeleteAttributesByConsentID_Call struct {
	*mock.Call
}

// DeleteAttributesByConsentID is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) DeleteAttributesByConsentID(tx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_DeleteAttributesByConsentID_Call {
	return &ConsentStore_DeleteAttributesByConsentID_Call{Call: _e.mock.On("DeleteAttributesByConsentID", tx, consentID, orgID)}
}

func (_c *ConsentStore_DeleteAttributesByConsentID_Call) Run(run func(tx model.TxInterface, consentID string, orgID string)) *ConsentStore_DeleteAttributesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_DeleteAttributesByConsentID_Call) Return(_a0 error) *ConsentStore_DeleteAttributesByConsentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_DeleteAttributesByConsentID_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentStore_DeleteAttributesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteElementApprovalsByConsentID provides a mock function with given fields: tx, consentID, orgID
func (_m *ConsentStore) DeleteElementApprovalsByConsentID(tx model.TxInterface, consentID string, orgID string) error {
	ret := _m.Called(tx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteElementApprovalsByConsentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, consentID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_DeleteElementApprovalsByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteElementApprovalsByConsentID'
type ConsentStore_DeleteElementApprovalsByConsentID_Call struct {
	*mock.Call
}

// DeleteElementApprovalsByConsentID is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) DeleteElementApprovalsByConsentID(tx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_DeleteElementApprovalsByConsentID_Call {
	return &ConsentStore_DeleteElementApprovalsByConsentID_Call{Call: _e.mock.On("DeleteElementApprovalsByConsentID", tx, consentID, orgID)}
}

func (_c *ConsentStore_DeleteElementApprovalsByConsentID_Call) Run(run func(tx model.TxInterface, consentID string, orgID string)) *ConsentStore_DeleteElementApprovalsByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_DeleteElementApprovalsByConsentID_Call) Return(_a0 error) *ConsentStore_DeleteElementApprovalsByConsentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_DeleteElementApprovalsByConsentID_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentStore_DeleteElementApprovalsByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePurposesByConsentID provides a mock function with given fields: tx, consentID, orgID
func (_m *ConsentStore) DeletePurposesByConsentID(tx model.TxInterface, consentID string, orgID string) error {
	ret := _m.Called(tx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurposesByConsentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string) error); ok {
		r0 = rf(tx, consentID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_DeletePurposesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePurposesByConsentID'
type ConsentStore_DeletePurposesByConsentID_Call struct {
	*mock.Call
}

// DeletePurposesByConsentID is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) DeletePurposesByConsentID(tx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_DeletePurposesByConsentID_Call {
	return &ConsentStore_DeletePurposesByConsentID_Call{Call: _e.mock.On("DeletePurposesByConsentID", tx, consentID, orgID)}
}

func (_c *ConsentStore_DeletePurposesByConsentID_Call) Run(run func(tx model.TxInterface, consentID string, orgID string)) *ConsentStore_DeletePurposesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_DeletePurposesByConsentID_Call) Return(_a0 error) *ConsentStore_DeletePurposesByConsentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_DeletePurposesByConsentID_Call) RunAndReturn(run func(model.TxInterface, string, string) error) *ConsentStore_DeletePurposesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttributesByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetAttributesByConsentID(ctx context.Context, consentID string, orgID string) ([]consentmodel.ConsentAttribute, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttributesByConsentID")
	}

	var r0 []consentmodel.ConsentAttribute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.ConsentAttribute, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.ConsentAttribute); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentAttribute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetAttributesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttributesByConsentID'
type ConsentStore_GetAttributesByConsentID_Call struct {
	*mock.Call
}

// GetAttributesByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetAttributesByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetAttributesByConsentID_Call {
	return &ConsentStore_GetAttributesByConsentID_Call{Call: _e.mock.On("GetAttributesByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetAttributesByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetAttributesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentID_Call) Return(_a0 []consentmodel.ConsentAttribute, _a1 error) *ConsentStore_GetAttributesByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.ConsentAttribute, error)) *ConsentStore_GetAttributesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttributesByConsentIDs provides a mock function with given fields: ctx, consentIDs, orgID
func (_m *ConsentStore) GetAttributesByConsentIDs(ctx context.Context, consentIDs []string, orgID string) (map[string]map[string]string, error) {
	ret := _m.Called(ctx, consentIDs, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttributesByConsentIDs")
	}

	var r0 map[string]map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) (map[string]map[string]string, error)); ok {
		return rf(ctx, consentIDs, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) map[string]map[string]string); ok {
		r0 = rf(ctx, consentIDs, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, consentIDs, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetAttributesByConsentIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttributesByConsentIDs'
type ConsentStore_GetAttributesByConsentIDs_Call struct {
	*mock.Call
}

// GetAttributesByConsentIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - consentIDs []string
//   - orgID string
func (_e *ConsentStore_Expecter) GetAttributesByConsentIDs(ctx interface{}, consentIDs interface{}, orgID interface{}) *ConsentStore_GetAttributesByConsentIDs_Call {
	return &ConsentStore_GetAttributesByConsentIDs_Call{Call: _e.mock.On("GetAttributesByConsentIDs", ctx, consentIDs, orgID)}
}

func (_c *ConsentStore_GetAttributesByConsentIDs_Call) Run(run func(ctx context.Context, consentIDs []string, orgID string)) *ConsentStore_GetAttributesByConsentIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentIDs_Call) Return(_a0 map[string]map[string]string, _a1 error) *ConsentStore_GetAttributesByConsentIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetAttributesByConsentIDs_Call) RunAndReturn(run func(context.Context, []string, string) (map[string]map[string]string, error)) *ConsentStore_GetAttributesByConsentIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetByID(ctx context.Context, consentID string, orgID string) (*consentmodel.Consent, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *consentmodel.Consent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*consentmodel.Consent, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *consentmodel.Consent); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consentmodel.Consent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ConsentStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetByID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetByID_Call {
	return &ConsentStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetByID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetByID_Call) Return(_a0 *consentmodel.Consent, _a1 error) *ConsentStore_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*consentmodel.Consent, error)) *ConsentStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetConsentIDsByAttribute provides a mock function with given fields: ctx, key, value, orgID
func (_m *ConsentStore) GetConsentIDsByAttribute(ctx context.Context, key string, value string, orgID string) ([]string, error) {
	ret := _m.Called(ctx, key, value, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetConsentIDsByAttribute")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]string, error)); ok {
		return rf(ctx, key, value, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []string); ok {
		r0 = rf(ctx, key, value, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, key, value, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetConsentIDsByAttribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConsentIDsByAttribute'
type ConsentStore_GetConsentIDsByAttribute_Call struct {
	*mock.Call
}

// GetConsentIDsByAttribute is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - orgID string
func (_e *ConsentStore_Expecter) GetConsentIDsByAttribute(ctx interface{}, key interface{}, value interface{}, orgID interface{}) *ConsentStore_GetConsentIDsByAttribute_Call {
	return &ConsentStore_GetConsentIDsByAttribute_Call{Call: _e.mock.On("GetConsentIDsByAttribute", ctx, key, value, orgID)}
}

func (_c *ConsentStore_GetConsentIDsByAttribute_Call) Run(run func(ctx context.Context, key string, value string, orgID string)) *ConsentStore_GetConsentIDsByAttribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ConsentStore_GetConsentIDsByAttribute_Call) Return(_a0 []string, _a1 error) *ConsentStore_GetConsentIDsByAttribute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetConsentIDsByAttribute_Call) RunAndReturn(run func(context.Context, string, string, string) ([]string, error)) *ConsentStore_GetConsentIDsByAttribute_Call {
	_c.Call.Return(run)
	return _c
}

// GetConsentIDsByAttributeKey provides a mock function with given fields: ctx, key, orgID
func (_m *ConsentStore) GetConsentIDsByAttributeKey(ctx context.Context, key string, orgID string) ([]string, error) {
	ret := _m.Called(ctx, key, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetConsentIDsByAttributeKey")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, key, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, key, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetConsentIDsByAttributeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConsentIDsByAttributeKey'
type ConsentStore_GetConsentIDsByAttributeKey_Call struct {
	*mock.Call
}

// GetConsentIDsByAttributeKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - orgID string
func (_e *ConsentStore_Expecter) GetConsentIDsByAttributeKey(ctx interface{}, key interface{}, orgID interface{}) *ConsentStore_GetConsentIDsByAttributeKey_Call {
	return &ConsentStore_GetConsentIDsByAttributeKey_Call{Call: _e.mock.On("GetConsentIDsByAttributeKey", ctx, key, orgID)}
}

func (_c *ConsentStore_GetConsentIDsByAttributeKey_Call) Run(run func(ctx context.Context, key string, orgID string)) *ConsentStore_GetConsentIDsByAttributeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetConsentIDsByAttributeKey_Call) Return(_a0 []string, _a1 error) *ConsentStore_GetConsentIDsByAttributeKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetConsentIDsByAttributeKey_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *ConsentStore_GetConsentIDsByAttributeKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetElementApprovalsByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetElementApprovalsByConsentID(ctx context.Context, consentID string, orgID string) ([]consentmodel.ConsentApprovalRow, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetElementApprovalsByConsentID")
	}

	var r0 []consentmodel.ConsentApprovalRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.ConsentApprovalRow, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.ConsentApprovalRow); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentApprovalRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetElementApprovalsByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetElementApprovalsByConsentID'
type ConsentStore_GetElementApprovalsByConsentID_Call struct {
	*mock.Call
}

// GetElementApprovalsByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetElementApprovalsByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetElementApprovalsByConsentID_Call {
	return &ConsentStore_GetElementApprovalsByConsentID_Call{Call: _e.mock.On("GetElementApprovalsByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetElementApprovalsByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetElementApprovalsByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetElementApprovalsByConsentID_Call) Return(_a0 []consentmodel.ConsentApprovalRow, _a1 error) *ConsentStore_GetElementApprovalsByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetElementApprovalsByConsentID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.ConsentApprovalRow, error)) *ConsentStore_GetElementApprovalsByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetElementPropertiesByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetElementPropertiesByConsentID(ctx context.Context, consentID string, orgID string) (map[string]map[string]string, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetElementPropertiesByConsentID")
	}

	var r0 map[string]map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (map[string]map[string]string, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) map[string]map[string]string); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetElementPropertiesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetElementPropertiesByConsentID'
type ConsentStore_GetElementPropertiesByConsentID_Call struct {
	*mock.Call
}

// GetElementPropertiesByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetElementPropertiesByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetElementPropertiesByConsentID_Call {
	return &ConsentStore_GetElementPropertiesByConsentID_Call{Call: _e.mock.On("GetElementPropertiesByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetElementPropertiesByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetElementPropertiesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetElementPropertiesByConsentID_Call) Return(_a0 map[string]map[string]string, _a1 error) *ConsentStore_GetElementPropertiesByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetElementPropertiesByConsentID_Call) RunAndReturn(run func(context.Context, string, string) (map[string]map[string]string, error)) *ConsentStore_GetElementPropertiesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPurposePropertiesByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetPurposePropertiesByConsentID(ctx context.Context, consentID string, orgID string) (map[string]map[string]string, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposePropertiesByConsentID")
	}

	var r0 map[string]map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (map[string]map[string]string, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) map[string]map[string]string); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetPurposePropertiesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPurposePropertiesByConsentID'
type ConsentStore_GetPurposePropertiesByConsentID_Call struct {
	*mock.Call
}

// GetPurposePropertiesByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetPurposePropertiesByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetPurposePropertiesByConsentID_Call {
	return &ConsentStore_GetPurposePropertiesByConsentID_Call{Call: _e.mock.On("GetPurposePropertiesByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetPurposePropertiesByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetPurposePropertiesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetPurposePropertiesByConsentID_Call) Return(_a0 map[string]map[string]string, _a1 error) *ConsentStore_GetPurposePropertiesByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetPurposePropertiesByConsentID_Call) RunAndReturn(run func(context.Context, string, string) (map[string]map[string]string, error)) *ConsentStore_GetPurposePropertiesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPurposesByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *ConsentStore) GetPurposesByConsentID(ctx context.Context, consentID string, orgID string) ([]consentmodel.ConsentPurposeRow, error) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposesByConsentID")
	}

	var r0 []consentmodel.ConsentPurposeRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]consentmodel.ConsentPurposeRow, error)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []consentmodel.ConsentPurposeRow); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.ConsentPurposeRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_GetPurposesByConsentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPurposesByConsentID'
type ConsentStore_GetPurposesByConsentID_Call struct {
	*mock.Call
}

// GetPurposesByConsentID is a helper method to define mock.On call
//   - ctx context.Context
//   - consentID string
//   - orgID string
func (_e *ConsentStore_Expecter) GetPurposesByConsentID(ctx interface{}, consentID interface{}, orgID interface{}) *ConsentStore_GetPurposesByConsentID_Call {
	return &ConsentStore_GetPurposesByConsentID_Call{Call: _e.mock.On("GetPurposesByConsentID", ctx, consentID, orgID)}
}

func (_c *ConsentStore_GetPurposesByConsentID_Call) Run(run func(ctx context.Context, consentID string, orgID string)) *ConsentStore_GetPurposesByConsentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_GetPurposesByConsentID_Call) Return(_a0 []consentmodel.ConsentPurposeRow, _a1 error) *ConsentStore_GetPurposesByConsentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_GetPurposesByConsentID_Call) RunAndReturn(run func(context.Context, string, string) ([]consentmodel.ConsentPurposeRow, error)) *ConsentStore_GetPurposesByConsentID_Call {
	_c.Call.Return(run)
	return _c
}

// IsPurposeUsedInConsents provides a mock function with given fields: ctx, purposeID, orgID
func (_m *ConsentStore) IsPurposeUsedInConsents(ctx context.Context, purposeID string, orgID string) (bool, error) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for IsPurposeUsedInConsents")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsentStore_IsPurposeUsedInConsents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPurposeUsedInConsents'
type ConsentStore_IsPurposeUsedInConsents_Call struct {
	*mock.Call
}

// IsPurposeUsedInConsents is a helper method to define mock.On call
//   - ctx context.Context
//   - purposeID string
//   - orgID string
func (_e *ConsentStore_Expecter) IsPurposeUsedInConsents(ctx interface{}, purposeID interface{}, orgID interface{}) *ConsentStore_IsPurposeUsedInConsents_Call {
	return &ConsentStore_IsPurposeUsedInConsents_Call{Call: _e.mock.On("IsPurposeUsedInConsents", ctx, purposeID, orgID)}
}

func (_c *ConsentStore_IsPurposeUsedInConsents_Call) Run(run func(ctx context.Context, purposeID string, orgID string)) *ConsentStore_IsPurposeUsedInConsents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConsentStore_IsPurposeUsedInConsents_Call) Return(_a0 bool, _a1 error) *ConsentStore_IsPurposeUsedInConsents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConsentStore_IsPurposeUsedInConsents_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *ConsentStore_IsPurposeUsedInConsents_Call {
	_c.Call.Return(run)
	return _c
}

// LinkPurposeVersionToConsent provides a mock function with given fields: tx, consentID, purposeVersionID, orgID
func (_m *ConsentStore) LinkPurposeVersionToConsent(tx model.TxInterface, consentID string, purposeVersionID string, orgID string) error {
	ret := _m.Called(tx, consentID, purposeVersionID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for LinkPurposeVersionToConsent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string, string) error); ok {
		r0 = rf(tx, consentID, purposeVersionID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_LinkPurposeVersionToConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkPurposeVersionToConsent'
type ConsentStore_LinkPurposeVersionToConsent_Call struct {
	*mock.Call
}

// LinkPurposeVersionToConsent is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - purposeVersionID string
//   - orgID string
func (_e *ConsentStore_Expecter) LinkPurposeVersionToConsent(tx interface{}, consentID interface{}, purposeVersionID interface{}, orgID interface{}) *ConsentStore_LinkPurposeVersionToConsent_Call {
	return &ConsentStore_LinkPurposeVersionToConsent_Call{Call: _e.mock.On("LinkPurposeVersionToConsent", tx, consentID, purposeVersionID, orgID)}
}

func (_c *ConsentStore_LinkPurposeVersionToConsent_Call) Run(run func(tx model.TxInterface, consentID string, purposeVersionID string, orgID string)) *ConsentStore_LinkPurposeVersionToConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ConsentStore_LinkPurposeVersionToConsent_Call) Return(_a0 error) *ConsentStore_LinkPurposeVersionToConsent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_LinkPurposeVersionToConsent_Call) RunAndReturn(run func(model.TxInterface, string, string, string) error) *ConsentStore_LinkPurposeVersionToConsent_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, filters
func (_m *ConsentStore) Search(ctx context.Context, filters consentmodel.ConsentSearchFilter) ([]consentmodel.Consent, int, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []consentmodel.Consent
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, consentmodel.ConsentSearchFilter) ([]consentmodel.Consent, int, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, consentmodel.ConsentSearchFilter) []consentmodel.Consent); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consentmodel.Consent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, consentmodel.ConsentSearchFilter) int); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, consentmodel.ConsentSearchFilter) error); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ConsentStore_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type ConsentStore_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - filters consentmodel.ConsentSearchFilter
func (_e *ConsentStore_Expecter) Search(ctx interface{}, filters interface{}) *ConsentStore_Search_Call {
	return &ConsentStore_Search_Call{Call: _e.mock.On("Search", ctx, filters)}
}

func (_c *ConsentStore_Search_Call) Run(run func(ctx context.Context, filters consentmodel.ConsentSearchFilter)) *ConsentStore_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(consentmodel.ConsentSearchFilter))
	})
	return _c
}

func (_c *ConsentStore_Search_Call) Return(_a0 []consentmodel.Consent, _a1 int, _a2 error) *ConsentStore_Search_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ConsentStore_Search_Call) RunAndReturn(run func(context.Context, consentmodel.ConsentSearchFilter) ([]consentmodel.Consent, int, error)) *ConsentStore_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: tx, consent
func (_m *ConsentStore) Update(tx model.TxInterface, consent *consentmodel.Consent) error {
	ret := _m.Called(tx, consent)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, *consentmodel.Consent) error); ok {
		r0 = rf(tx, consent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ConsentStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consent *consentmodel.Consent
func (_e *ConsentStore_Expecter) Update(tx interface{}, consent interface{}) *ConsentStore_Update_Call {
	return &ConsentStore_Update_Call{Call: _e.mock.On("Update", tx, consent)}
}

func (_c *ConsentStore_Update_Call) Run(run func(tx model.TxInterface, consent *consentmodel.Consent)) *ConsentStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(*consentmodel.Consent))
	})
	return _c
}

func (_c *ConsentStore_Update_Call) Return(_a0 error) *ConsentStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_Update_Call) RunAndReturn(run func(model.TxInterface, *consentmodel.Consent) error) *ConsentStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: tx, consentID, orgID, status, updatedTime
func (_m *ConsentStore) UpdateStatus(tx model.TxInterface, consentID string, orgID string, status string, updatedTime int64) error {
	ret := _m.Called(tx, consentID, orgID, status, updatedTime)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TxInterface, string, string, string, int64) error); ok {
		r0 = rf(tx, consentID, orgID, status, updatedTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsentStore_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type ConsentStore_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - tx model.TxInterface
//   - consentID string
//   - orgID string
//   - status string
//   - updatedTime int64
func (_e *ConsentStore_Expecter) UpdateStatus(tx interface{}, consentID interface{}, orgID interface{}, status interface{}, updatedTime interface{}) *ConsentStore_UpdateStatus_Call {
	return &ConsentStore_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", tx, consentID, orgID, status, updatedTime)}
}

func (_c *ConsentStore_UpdateStatus_Call) Run(run func(tx model.TxInterface, consentID string, orgID string, status string, updatedTime int64)) *ConsentStore_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TxInterface), args[1].(string), args[2].(string), args[3].(string), args[4].(int64))
	})
	return _c
}

func (_c *ConsentStore_UpdateStatus_Call) Return(_a0 error) *ConsentStore_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsentStore_UpdateStatus_Call) RunAndReturn(run func(model.TxInterface, string, string, string, int64) error) *ConsentStore_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsentStore creates a new instance of ConsentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsentStore {
	mock := &ConsentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
