// Code generated by mockery v2.53.5. DO NOT EDIT.

package modelmock

import (
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wso2/openfgc/internal/system/database/model"
)

// TxInterface is an autogenerated mock type for the TxInterface type
type TxInterface struct {
	mock.Mock
}

type TxInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *TxInterface) EXPECT() *TxInterface_Expecter {
	return &TxInterface_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with no fields
func (_m *TxInterface) Commit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxInterface_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type TxInterface_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *TxInterface_Expecter) Commit() *TxInterface_Commit_Call {
	return &TxInterface_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *TxInterface_Commit_Call) Run(run func()) *TxInterface_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TxInterface_Commit_Call) Return(_a0 error) *TxInterface_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxInterface_Commit_Call) RunAndReturn(run func() error) *TxInterface_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function with given fields: query, args
func (_m *TxInterface) Exec(query model.DBQuery, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) (sql.Result, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) sql.Result); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(model.DBQuery, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxInterface_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type TxInterface_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query model.DBQuery
//   - args ...interface{}
func (_e *TxInterface_Expecter) Exec(query interface{}, args ...interface{}) *TxInterface_Exec_Call {
	return &TxInterface_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{query}, args...)...)}
}

func (_c *TxInterface_Exec_Call) Run(run func(query model.DBQuery, args ...interface{})) *TxInterface_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(model.DBQuery), variadicArgs...)
	})
	return _c
}

func (_c *TxInterface_Exec_Call) Return(_a0 sql.Result, _a1 error) *TxInterface_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxInterface_Exec_Call) RunAndReturn(run func(model.DBQuery, ...interface{}) (sql.Result, error)) *TxInterface_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: query, args
func (_m *TxInterface) Query(query model.DBQuery, args ...interface{}) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) (*sql.Rows, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) *sql.Rows); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(model.DBQuery, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxInterface_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type TxInterface_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query model.DBQuery
//   - args ...interface{}
func (_e *TxInterface_Expecter) Query(query interface{}, args ...interface{}) *TxInterface_Query_Call {
	return &TxInterface_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{query}, args...)...)}
}

func (_c *TxInterface_Query_Call) Run(run func(query model.DBQuery, args ...interface{})) *TxInterface_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(model.DBQuery), variadicArgs...)
	})
	return _c
}

func (_c *TxInterface_Query_Call) Return(_a0 *sql.Rows, _a1 error) *TxInterface_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxInterface_Query_Call) RunAndReturn(run func(model.DBQuery, ...interface{}) (*sql.Rows, error)) *TxInterface_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with no fields
func (_m *TxInterface) Rollback() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxInterface_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type TxInterface_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *TxInterface_Expecter) Rollback() *TxInterface_Rollback_Call {
	return &TxInterface_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *TxInterface_Rollback_Call) Run(run func()) *TxInterface_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TxInterface_Rollback_Call) Return(_a0 error) *TxInterface_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxInterface_Rollback_Call) RunAndReturn(run func() error) *TxInterface_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewTxInterface creates a new instance of TxInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxInterface {
	mock := &TxInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
