// Code generated by mockery v2.53.5. DO NOT EDIT.

package consentelement

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wso2/openfgc/internal/consentelement/model"

	serviceerror "github.com/wso2/openfgc/internal/system/error/serviceerror"
)

// MockConsentElementService is an autogenerated mock type for the ConsentElementService type
type MockConsentElementService struct {
	mock.Mock
}

type MockConsentElementService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsentElementService) EXPECT() *MockConsentElementService_Expecter {
	return &MockConsentElementService_Expecter{mock: &_m.Mock}
}

// CreateElementsInBatch provides a mock function with given fields: ctx, requests, orgID
func (_m *MockConsentElementService) CreateElementsInBatch(ctx context.Context, requests []model.ConsentElementCreateRequest, orgID string) ([]model.ConsentElement, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, requests, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CreateElementsInBatch")
	}

	var r0 []model.ConsentElement
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, []model.ConsentElementCreateRequest, string) ([]model.ConsentElement, *serviceerror.ServiceError)); ok {
		return rf(ctx, requests, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []model.ConsentElementCreateRequest, string) []model.ConsentElement); ok {
		r0 = rf(ctx, requests, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ConsentElement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []model.ConsentElementCreateRequest, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, requests, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockConsentElementService_CreateElementsInBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateElementsInBatch'
type MockConsentElementService_CreateElementsInBatch_Call struct {
	*mock.Call
}

// CreateElementsInBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - requests []model.ConsentElementCreateRequest
//   - orgID string
func (_e *MockConsentElementService_Expecter) CreateElementsInBatch(ctx interface{}, requests interface{}, orgID interface{}) *MockConsentElementService_CreateElementsInBatch_Call {
	return &MockConsentElementService_CreateElementsInBatch_Call{Call: _e.mock.On("CreateElementsInBatch", ctx, requests, orgID)}
}

func (_c *MockConsentElementService_CreateElementsInBatch_Call) Run(run func(ctx context.Context, requests []model.ConsentElementCreateRequest, orgID string)) *MockConsentElementService_CreateElementsInBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.ConsentElementCreateRequest), args[2].(string))
	})
	return _c
}

func (_c *MockConsentElementService_CreateElementsInBatch_Call) Return(_a0 []model.ConsentElement, _a1 *serviceerror.ServiceError) *MockConsentElementService_CreateElementsInBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConsentElementService_CreateElementsInBatch_Call) RunAndReturn(run func(context.Context, []model.ConsentElementCreateRequest, string) ([]model.ConsentElement, *serviceerror.ServiceError)) *MockConsentElementService_CreateElementsInBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteElement provides a mock function with given fields: ctx, elementID, orgID
func (_m *MockConsentElementService) DeleteElement(ctx context.Context, elementID string, orgID string) *serviceerror.ServiceError {
	ret := _m.Called(ctx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteElement")
	}

	var r0 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r0 = rf(ctx, elementID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}

	return r0
}

// MockConsentElementService_DeleteElement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteElement'
type MockConsentElementService_DeleteElement_Call struct {
	*mock.Call
}

// DeleteElement is a helper method to define mock.On call
//   - ctx context.Context
//   - elementID string
//   - orgID string
func (_e *MockConsentElementService_Expecter) DeleteElement(ctx interface{}, elementID interface{}, orgID interface{}) *MockConsentElementService_DeleteElement_Call {
	return &MockConsentElementService_DeleteElement_Call{Call: _e.mock.On("DeleteElement", ctx, elementID, orgID)}
}

func (_c *MockConsentElementService_DeleteElement_Call) Run(run func(ctx context.Context, elementID string, orgID string)) *MockConsentElementService_DeleteElement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockConsentElementService_DeleteElement_Call) Return(_a0 *serviceerror.ServiceError) *MockConsentElementService_DeleteElement_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsentElementService_DeleteElement_Call) RunAndReturn(run func(context.Context, string, string) *serviceerror.ServiceError) *MockConsentElementService_DeleteElement_Call {
	_c.Call.Return(run)
	return _c
}

// GetElement provides a mock function with given fields: ctx, elementID, orgID
func (_m *MockConsentElementService) GetElement(ctx context.Context, elementID string, orgID string) (*model.ConsentElement, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, elementID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetElement")
	}

	var r0 *model.ConsentElement
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.ConsentElement, *serviceerror.ServiceError)); ok {
		return rf(ctx, elementID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.ConsentElement); ok {
		r0 = rf(ctx, elementID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentElement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, elementID, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockConsentElementService_GetElement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetElement'
type MockConsentElementService_GetElement_Call struct {
	*mock.Call
}

// GetElement is a helper method to define mock.On call
//   - ctx context.Context
//   - elementID string
//   - orgID string
func (_e *MockConsentElementService_Expecter) GetElement(ctx interface{}, elementID interface{}, orgID interface{}) *MockConsentElementService_GetElement_Call {
	return &MockConsentElementService_GetElement_Call{Call: _e.mock.On("GetElement", ctx, elementID, orgID)}
}

func (_c *MockConsentElementService_GetElement_Call) Run(run func(ctx context.Context, elementID string, orgID string)) *MockConsentElementService_GetElement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockConsentElementService_GetElement_Call) Return(_a0 *model.ConsentElement, _a1 *serviceerror.ServiceError) *MockConsentElementService_GetElement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConsentElementService_GetElement_Call) RunAndReturn(run func(context.Context, string, string) (*model.ConsentElement, *serviceerror.ServiceError)) *MockConsentElementService_GetElement_Call {
	_c.Call.Return(run)
	return _c
}

// ListElements provides a mock function with given fields: ctx, orgID, limit, offset, name
func (_m *MockConsentElementService) ListElements(ctx context.Context, orgID string, limit int, offset int, name string) ([]model.ConsentElement, int, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, orgID, limit, offset, name)

	if len(ret) == 0 {
		panic("no return value specified for ListElements")
	}

	var r0 []model.ConsentElement
	var r1 int
	var r2 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) ([]model.ConsentElement, int, *serviceerror.ServiceError)); ok {
		return rf(ctx, orgID, limit, offset, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) []model.ConsentElement); ok {
		r0 = rf(ctx, orgID, limit, offset, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ConsentElement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, string) int); ok {
		r1 = rf(ctx, orgID, limit, offset, name)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, string) *serviceerror.ServiceError); ok {
		r2 = rf(ctx, orgID, limit, offset, name)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*serviceerror.ServiceError)
		}
	}

	return r0, r1, r2
}

// MockConsentElementService_ListElements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListElements'
type MockConsentElementService_ListElements_Call struct {
	*mock.Call
}

// ListElements is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - limit int
//   - offset int
//   - name string
func (_e *MockConsentElementService_Expecter) ListElements(ctx interface{}, orgID interface{}, limit interface{}, offset interface{}, name interface{}) *MockConsentElementService_ListElements_Call {
	return &MockConsentElementService_ListElements_Call{Call: _e.mock.On("ListElements", ctx, orgID, limit, offset, name)}
}

func (_c *MockConsentElementService_ListElements_Call) Run(run func(ctx context.Context, orgID string, limit int, offset int, name string)) *MockConsentElementService_ListElements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *MockConsentElementService_ListElements_Call) Return(_a0 []model.ConsentElement, _a1 int, _a2 *serviceerror.ServiceError) *MockConsentElementService_ListElements_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockConsentElementService_ListElements_Call) RunAndReturn(run func(context.Context, string, int, int, string) ([]model.ConsentElement, int, *serviceerror.ServiceError)) *MockConsentElementService_ListElements_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateElement provides a mock function with given fields: ctx, elementID, req, orgID
func (_m *MockConsentElementService) UpdateElement(ctx context.Context, elementID string, req model.ConsentElementUpdateRequest, orgID string) (*model.ConsentElement, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, elementID, req, orgID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateElement")
	}

	var r0 *model.ConsentElement
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ConsentElementUpdateRequest, string) (*model.ConsentElement, *serviceerror.ServiceError)); ok {
		return rf(ctx, elementID, req, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ConsentElementUpdateRequest, string) *model.ConsentElement); ok {
		r0 = rf(ctx, elementID, req, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentElement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.ConsentElementUpdateRequest, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, elementID, req, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockConsentElementService_UpdateElement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateElement'
type MockConsentElementService_UpdateElement_Call struct {
	*mock.Call
}

// UpdateElement is a helper method to define mock.On call
//   - ctx context.Context
//   - elementID string
//   - req model.ConsentElementUpdateRequest
//   - orgID string
func (_e *MockConsentElementService_Expecter) UpdateElement(ctx interface{}, elementID interface{}, req interface{}, orgID interface{}) *MockConsentElementService_UpdateElement_Call {
	return &MockConsentElementService_UpdateElement_Call{Call: _e.mock.On("UpdateElement", ctx, elementID, req, orgID)}
}

func (_c *MockConsentElementService_UpdateElement_Call) Run(run func(ctx context.Context, elementID string, req model.ConsentElementUpdateRequest, orgID string)) *MockConsentElementService_UpdateElement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.ConsentElementUpdateRequest), args[3].(string))
	})
	return _c
}

func (_c *MockConsentElementService_UpdateElement_Call) Return(_a0 *model.ConsentElement, _a1 *serviceerror.ServiceError) *MockConsentElementService_UpdateElement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConsentElementService_UpdateElement_Call) RunAndReturn(run func(context.Context, string, model.ConsentElementUpdateRequest, string) (*model.ConsentElement, *serviceerror.ServiceError)) *MockConsentElementService_UpdateElement_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateElementNames provides a mock function with given fields: ctx, orgID, elementNames
func (_m *MockConsentElementService) ValidateElementNames(ctx context.Context, orgID string, elementNames []string) ([]string, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, orgID, elementNames)

	if len(ret) == 0 {
		panic("no return value specified for ValidateElementNames")
	}

	var r0 []string
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) ([]string, *serviceerror.ServiceError)); ok {
		return rf(ctx, orgID, elementNames)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) []string); ok {
		r0 = rf(ctx, orgID, elementNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, orgID, elementNames)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockConsentElementService_ValidateElementNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateElementNames'
type MockConsentElementService_ValidateElementNames_Call struct {
	*mock.Call
}

// ValidateElementNames is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - elementNames []string
func (_e *MockConsentElementService_Expecter) ValidateElementNames(ctx interface{}, orgID interface{}, elementNames interface{}) *MockConsentElementService_ValidateElementNames_Call {
	return &MockConsentElementService_ValidateElementNames_Call{Call: _e.mock.On("ValidateElementNames", ctx, orgID, elementNames)}
}

func (_c *MockConsentElementService_ValidateElementNames_Call) Run(run func(ctx context.Context, orgID string, elementNames []string)) *MockConsentElementService_ValidateElementNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockConsentElementService_ValidateElementNames_Call) Return(_a0 []string, _a1 *serviceerror.ServiceError) *MockConsentElementService_ValidateElementNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConsentElementService_ValidateElementNames_Call) RunAndReturn(run func(context.Context, string, []string) ([]string, *serviceerror.ServiceError)) *MockConsentElementService_ValidateElementNames_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsentElementService creates a new instance of MockConsentElementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsentElementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsentElementService {
	mock := &MockConsentElementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
