// Code generated by mockery v2.53.5. DO NOT EDIT.

package consent

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wso2/openfgc/internal/consent/model"

	serviceerror "github.com/wso2/openfgc/internal/system/error/serviceerror"
)

// MockConsentService is an autogenerated mock type for the ConsentService type
type MockConsentService struct {
	mock.Mock
}

// CreateConsent provides a mock function with given fields: ctx, req, clientID, orgID
func (_m *MockConsentService) CreateConsent(ctx context.Context, req model.ConsentAPIRequest, clientID string, orgID string) (*model.ConsentResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, req, clientID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CreateConsent")
	}

	var r0 *model.ConsentResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, model.ConsentAPIRequest, string, string) (*model.ConsentResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, req, clientID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ConsentAPIRequest, string, string) *model.ConsentResponse); ok {
		r0 = rf(ctx, req, clientID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ConsentAPIRequest, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, req, clientID, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// GetConsent provides a mock function with given fields: ctx, consentID, orgID
func (_m *MockConsentService) GetConsent(ctx context.Context, consentID string, orgID string) (*model.ConsentResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetConsent")
	}

	var r0 *model.ConsentResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.ConsentResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.ConsentResponse); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// RevokeConsent provides a mock function with given fields: ctx, consentID, orgID, req
func (_m *MockConsentService) RevokeConsent(ctx context.Context, consentID string, orgID string, req model.ConsentRevokeRequest) (*model.ConsentRevokeResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, consentID, orgID, req)

	if len(ret) == 0 {
		panic("no return value specified for RevokeConsent")
	}

	var r0 *model.ConsentRevokeResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.ConsentRevokeRequest) (*model.ConsentRevokeResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, consentID, orgID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.ConsentRevokeRequest) *model.ConsentRevokeResponse); ok {
		r0 = rf(ctx, consentID, orgID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentRevokeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.ConsentRevokeRequest) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, consentID, orgID, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// SearchConsentsByAttribute provides a mock function with given fields: ctx, key, value, orgID
func (_m *MockConsentService) SearchConsentsByAttribute(ctx context.Context, key string, value string, orgID string) (*model.ConsentAttributeSearchResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, key, value, orgID)

	if len(ret) == 0 {
		panic("no return value specified for SearchConsentsByAttribute")
	}

	var r0 *model.ConsentAttributeSearchResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.ConsentAttributeSearchResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, key, value, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.ConsentAttributeSearchResponse); ok {
		r0 = rf(ctx, key, value, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentAttributeSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, key, value, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// SearchConsentsDetailed provides a mock function with given fields: ctx, filters
func (_m *MockConsentService) SearchConsentsDetailed(ctx context.Context, filters model.ConsentSearchFilters) (*model.ConsentDetailSearchResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for SearchConsentsDetailed")
	}

	var r0 *model.ConsentDetailSearchResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, model.ConsentSearchFilters) (*model.ConsentDetailSearchResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ConsentSearchFilters) *model.ConsentDetailSearchResponse); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentDetailSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ConsentSearchFilters) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, filters)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// UpdateConsent provides a mock function with given fields: ctx, req, clientID, orgID, consentID
func (_m *MockConsentService) UpdateConsent(ctx context.Context, req model.ConsentAPIUpdateRequest, clientID string, orgID string, consentID string) (*model.ConsentResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, req, clientID, orgID, consentID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConsent")
	}

	var r0 *model.ConsentResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, model.ConsentAPIUpdateRequest, string, string, string) (*model.ConsentResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, req, clientID, orgID, consentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ConsentAPIUpdateRequest, string, string, string) *model.ConsentResponse); ok {
		r0 = rf(ctx, req, clientID, orgID, consentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ConsentAPIUpdateRequest, string, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, req, clientID, orgID, consentID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// ValidateConsent provides a mock function with given fields: ctx, req, orgID
func (_m *MockConsentService) ValidateConsent(ctx context.Context, req model.ValidateRequest, orgID string) (*model.ValidateResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, req, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateConsent")
	}

	var r0 *model.ValidateResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, model.ValidateRequest, string) (*model.ValidateResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, req, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ValidateRequest, string) *model.ValidateResponse); ok {
		r0 = rf(ctx, req, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ValidateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ValidateRequest, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, req, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// NewMockConsentService creates a new instance of MockConsentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsentService {
	mock := &MockConsentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
