// Code generated by mockery v2.53.5. DO NOT EDIT.

package consentpurpose

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wso2/openfgc/internal/consentpurpose/model"

	serviceerror "github.com/wso2/openfgc/internal/system/error/serviceerror"
)

// MockConsentPurposeService is an autogenerated mock type for the ConsentPurposeService type
type MockConsentPurposeService struct {
	mock.Mock
}

// CreatePurpose provides a mock function with given fields: ctx, req, orgID, clientID
func (_m *MockConsentPurposeService) CreatePurpose(ctx context.Context, req model.CreateRequest, orgID string, clientID string) (*model.ConsentPurpose, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, req, orgID, clientID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurpose")
	}

	var r0 *model.ConsentPurpose
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateRequest, string, string) (*model.ConsentPurpose, *serviceerror.ServiceError)); ok {
		return rf(ctx, req, orgID, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateRequest, string, string) *model.ConsentPurpose); ok {
		r0 = rf(ctx, req, orgID, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateRequest, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, req, orgID, clientID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// DeletePurpose provides a mock function with given fields: ctx, purposeID, orgID
func (_m *MockConsentPurposeService) DeletePurpose(ctx context.Context, purposeID string, orgID string) *serviceerror.ServiceError {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurpose")
	}

	var r0 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}

	return r0
}

// GetPurpose provides a mock function with given fields: ctx, purposeID, orgID
func (_m *MockConsentPurposeService) GetPurpose(ctx context.Context, purposeID string, orgID string) (*model.ConsentPurpose, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurpose")
	}

	var r0 *model.ConsentPurpose
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.ConsentPurpose, *serviceerror.ServiceError)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.ConsentPurpose); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// ListPurposes provides a mock function with given fields: ctx, orgID, name, clientIDs, elementNames, offset, limit
func (_m *MockConsentPurposeService) ListPurposes(ctx context.Context, orgID string, name string, clientIDs []string, elementNames []string, offset int, limit int) ([]model.ConsentPurpose, int, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, orgID, name, clientIDs, elementNames, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPurposes")
	}

	var r0 []model.ConsentPurpose
	var r1 int
	var r2 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string, []string, int, int) ([]model.ConsentPurpose, int, *serviceerror.ServiceError)); ok {
		return rf(ctx, orgID, name, clientIDs, elementNames, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string, []string, int, int) []model.ConsentPurpose); ok {
		r0 = rf(ctx, orgID, name, clientIDs, elementNames, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ConsentPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string, []string, int, int) int); ok {
		r1 = rf(ctx, orgID, name, clientIDs, elementNames, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, []string, []string, int, int) *serviceerror.ServiceError); ok {
		r2 = rf(ctx, orgID, name, clientIDs, elementNames, offset, limit)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*serviceerror.ServiceError)
		}
	}

	return r0, r1, r2
}

// UpdatePurpose provides a mock function with given fields: ctx, purposeID, req, orgID, clientID
func (_m *MockConsentPurposeService) UpdatePurpose(ctx context.Context, purposeID string, req model.UpdateRequest, orgID string, clientID string) (*model.ConsentPurpose, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, purposeID, req, orgID, clientID)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePurpose")
	}

	var r0 *model.ConsentPurpose
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UpdateRequest, string, string) (*model.ConsentPurpose, *serviceerror.ServiceError)); ok {
		return rf(ctx, purposeID, req, orgID, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UpdateRequest, string, string) *model.ConsentPurpose); ok {
		r0 = rf(ctx, purposeID, req, orgID, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.UpdateRequest, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, purposeID, req, orgID, clientID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// NewMockConsentPurposeService creates a new instance of MockConsentPurposeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsentPurposeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsentPurposeService {
	mock := &MockConsentPurposeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
