// Code generated by mockery v2.53.5. DO NOT EDIT.

package consentpurpose

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wso2/openfgc/consent-server/internal/consentpurpose/model"

	serviceerror "github.com/wso2/openfgc/consent-server/internal/system/error/serviceerror"
)

// MockConsentPurposeService is an autogenerated mock type for the ConsentPurposeService type
type MockConsentPurposeService struct {
	mock.Mock
}

// CreatePurpose provides a mock function with given fields: ctx, input, orgID
func (_m *MockConsentPurposeService) CreatePurpose(ctx context.Context, input model.CreatePurposeInput, orgID string) (*model.PurposeOutput, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, input, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurpose")
	}

	var r0 *model.PurposeOutput
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, model.CreatePurposeInput, string) (*model.PurposeOutput, *serviceerror.ServiceError)); ok {
		return rf(ctx, input, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreatePurposeInput, string) *model.PurposeOutput); ok {
		r0 = rf(ctx, input, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PurposeOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreatePurposeInput, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, input, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// CreatePurposeVersion provides a mock function with given fields: ctx, purposeID, input, orgID
func (_m *MockConsentPurposeService) CreatePurposeVersion(ctx context.Context, purposeID string, input model.CreatePurposeVersionInput, orgID string) (*model.PurposeOutput, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, purposeID, input, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurposeVersion")
	}

	var r0 *model.PurposeOutput
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CreatePurposeVersionInput, string) (*model.PurposeOutput, *serviceerror.ServiceError)); ok {
		return rf(ctx, purposeID, input, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CreatePurposeVersionInput, string) *model.PurposeOutput); ok {
		r0 = rf(ctx, purposeID, input, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PurposeOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.CreatePurposeVersionInput, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, purposeID, input, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// DeletePurpose provides a mock function with given fields: ctx, purposeID, orgID
func (_m *MockConsentPurposeService) DeletePurpose(ctx context.Context, purposeID string, orgID string) *serviceerror.ServiceError {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurpose")
	}

	var r0 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}

	return r0
}

// DeletePurposeVersion provides a mock function with given fields: ctx, purposeID, version, orgID
func (_m *MockConsentPurposeService) DeletePurposeVersion(ctx context.Context, purposeID string, version int, orgID string) *serviceerror.ServiceError {
	ret := _m.Called(ctx, purposeID, version, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurposeVersion")
	}

	var r0 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) *serviceerror.ServiceError); ok {
		r0 = rf(ctx, purposeID, version, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}

	return r0
}

// GetPurpose provides a mock function with given fields: ctx, purposeID, orgID
func (_m *MockConsentPurposeService) GetPurpose(ctx context.Context, purposeID string, orgID string) (*model.PurposeOutput, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurpose")
	}

	var r0 *model.PurposeOutput
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.PurposeOutput, *serviceerror.ServiceError)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.PurposeOutput); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PurposeOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// GetPurposeVersion provides a mock function with given fields: ctx, purposeID, version, orgID
func (_m *MockConsentPurposeService) GetPurposeVersion(ctx context.Context, purposeID string, version int, orgID string) (*model.PurposeOutput, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, purposeID, version, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposeVersion")
	}

	var r0 *model.PurposeOutput
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) (*model.PurposeOutput, *serviceerror.ServiceError)); ok {
		return rf(ctx, purposeID, version, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) *model.PurposeOutput); ok {
		r0 = rf(ctx, purposeID, version, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PurposeOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, purposeID, version, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// GetPurposeVersions provides a mock function with given fields: ctx, purposeID, orgID
func (_m *MockConsentPurposeService) GetPurposeVersions(ctx context.Context, purposeID string, orgID string) (*model.PurposeVersionListOutput, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, purposeID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPurposeVersions")
	}

	var r0 *model.PurposeVersionListOutput
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.PurposeVersionListOutput, *serviceerror.ServiceError)); ok {
		return rf(ctx, purposeID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.PurposeVersionListOutput); ok {
		r0 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PurposeVersionListOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, purposeID, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// ListPurposes provides a mock function with given fields: ctx, orgID, filters
func (_m *MockConsentPurposeService) ListPurposes(ctx context.Context, orgID string, filters model.PurposeListFilter) (*model.PurposeListOutput, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, orgID, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListPurposes")
	}

	var r0 *model.PurposeListOutput
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PurposeListFilter) (*model.PurposeListOutput, *serviceerror.ServiceError)); ok {
		return rf(ctx, orgID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PurposeListFilter) *model.PurposeListOutput); ok {
		r0 = rf(ctx, orgID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PurposeListOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.PurposeListFilter) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, orgID, filters)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// NewMockConsentPurposeService creates a new instance of MockConsentPurposeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsentPurposeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsentPurposeService {
	mock := &MockConsentPurposeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
