// Code generated by mockery v2.53.5. DO NOT EDIT.

package providermock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wso2/openfgc/internal/system/database/model"

	transaction "github.com/wso2/openfgc/internal/system/database/transaction"
)

// DBClientInterface is an autogenerated mock type for the DBClientInterface type
type DBClientInterface struct {
	mock.Mock
}

type DBClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *DBClientInterface) EXPECT() *DBClientInterface_Expecter {
	return &DBClientInterface_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with no fields
func (_m *DBClientInterface) BeginTx() (model.TxInterface, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 model.TxInterface
	var r1 error
	if rf, ok := ret.Get(0).(func() (model.TxInterface, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() model.TxInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.TxInterface)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBClientInterface_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type DBClientInterface_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
func (_e *DBClientInterface_Expecter) BeginTx() *DBClientInterface_BeginTx_Call {
	return &DBClientInterface_BeginTx_Call{Call: _e.mock.On("BeginTx")}
}

func (_c *DBClientInterface_BeginTx_Call) Run(run func()) *DBClientInterface_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBClientInterface_BeginTx_Call) Return(_a0 model.TxInterface, _a1 error) *DBClientInterface_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBClientInterface_BeginTx_Call) RunAndReturn(run func() (model.TxInterface, error)) *DBClientInterface_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: query, args
func (_m *DBClientInterface) Execute(query model.DBQuery, args ...interface{}) (int64, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) (int64, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) int64); ok {
		r0 = rf(query, args...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(model.DBQuery, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBClientInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DBClientInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - query model.DBQuery
//   - args ...interface{}
func (_e *DBClientInterface_Expecter) Execute(query interface{}, args ...interface{}) *DBClientInterface_Execute_Call {
	return &DBClientInterface_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{query}, args...)...)}
}

func (_c *DBClientInterface_Execute_Call) Run(run func(query model.DBQuery, args ...interface{})) *DBClientInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(model.DBQuery), variadicArgs...)
	})
	return _c
}

func (_c *DBClientInterface_Execute_Call) Return(_a0 int64, _a1 error) *DBClientInterface_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBClientInterface_Execute_Call) RunAndReturn(run func(model.DBQuery, ...interface{}) (int64, error)) *DBClientInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteContext provides a mock function with given fields: ctx, query, args
func (_m *DBClientInterface) ExecuteContext(ctx context.Context, query model.DBQuery, args ...interface{}) (int64, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteContext")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.DBQuery, ...interface{}) (int64, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.DBQuery, ...interface{}) int64); ok {
		r0 = rf(ctx, query, args...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.DBQuery, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBClientInterface_ExecuteContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteContext'
type DBClientInterface_ExecuteContext_Call struct {
	*mock.Call
}

// ExecuteContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query model.DBQuery
//   - args ...interface{}
func (_e *DBClientInterface_Expecter) ExecuteContext(ctx interface{}, query interface{}, args ...interface{}) *DBClientInterface_ExecuteContext_Call {
	return &DBClientInterface_ExecuteContext_Call{Call: _e.mock.On("ExecuteContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *DBClientInterface_ExecuteContext_Call) Run(run func(ctx context.Context, query model.DBQuery, args ...interface{})) *DBClientInterface_ExecuteContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(model.DBQuery), variadicArgs...)
	})
	return _c
}

func (_c *DBClientInterface_ExecuteContext_Call) Return(_a0 int64, _a1 error) *DBClientInterface_ExecuteContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBClientInterface_ExecuteContext_Call) RunAndReturn(run func(context.Context, model.DBQuery, ...interface{}) (int64, error)) *DBClientInterface_ExecuteContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactioner provides a mock function with no fields
func (_m *DBClientInterface) GetTransactioner() (transaction.Transactioner, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTransactioner")
	}

	var r0 transaction.Transactioner
	var r1 error
	if rf, ok := ret.Get(0).(func() (transaction.Transactioner, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() transaction.Transactioner); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transaction.Transactioner)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBClientInterface_GetTransactioner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactioner'
type DBClientInterface_GetTransactioner_Call struct {
	*mock.Call
}

// GetTransactioner is a helper method to define mock.On call
func (_e *DBClientInterface_Expecter) GetTransactioner() *DBClientInterface_GetTransactioner_Call {
	return &DBClientInterface_GetTransactioner_Call{Call: _e.mock.On("GetTransactioner")}
}

func (_c *DBClientInterface_GetTransactioner_Call) Run(run func()) *DBClientInterface_GetTransactioner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBClientInterface_GetTransactioner_Call) Return(_a0 transaction.Transactioner, _a1 error) *DBClientInterface_GetTransactioner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBClientInterface_GetTransactioner_Call) RunAndReturn(run func() (transaction.Transactioner, error)) *DBClientInterface_GetTransactioner_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: query, args
func (_m *DBClientInterface) Query(query model.DBQuery, args ...interface{}) ([]map[string]interface{}, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) ([]map[string]interface{}, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) []map[string]interface{}); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(model.DBQuery, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBClientInterface_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type DBClientInterface_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query model.DBQuery
//   - args ...interface{}
func (_e *DBClientInterface_Expecter) Query(query interface{}, args ...interface{}) *DBClientInterface_Query_Call {
	return &DBClientInterface_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{query}, args...)...)}
}

func (_c *DBClientInterface_Query_Call) Run(run func(query model.DBQuery, args ...interface{})) *DBClientInterface_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(model.DBQuery), variadicArgs...)
	})
	return _c
}

func (_c *DBClientInterface_Query_Call) Return(_a0 []map[string]interface{}, _a1 error) *DBClientInterface_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBClientInterface_Query_Call) RunAndReturn(run func(model.DBQuery, ...interface{}) ([]map[string]interface{}, error)) *DBClientInterface_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *DBClientInterface) QueryContext(ctx context.Context, query model.DBQuery, args ...interface{}) ([]map[string]interface{}, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.DBQuery, ...interface{}) ([]map[string]interface{}, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.DBQuery, ...interface{}) []map[string]interface{}); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.DBQuery, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBClientInterface_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type DBClientInterface_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query model.DBQuery
//   - args ...interface{}
func (_e *DBClientInterface_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *DBClientInterface_QueryContext_Call {
	return &DBClientInterface_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *DBClientInterface_QueryContext_Call) Run(run func(ctx context.Context, query model.DBQuery, args ...interface{})) *DBClientInterface_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(model.DBQuery), variadicArgs...)
	})
	return _c
}

func (_c *DBClientInterface_QueryContext_Call) Return(_a0 []map[string]interface{}, _a1 error) *DBClientInterface_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBClientInterface_QueryContext_Call) RunAndReturn(run func(context.Context, model.DBQuery, ...interface{}) ([]map[string]interface{}, error)) *DBClientInterface_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewDBClientInterface creates a new instance of DBClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBClientInterface {
	mock := &DBClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
