/*
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package model

// =============================================================================
// DB types — store layer only, db tags, no json tags
// =============================================================================

// ConsentStatusAudit is one row from the CONSENT_STATUS_AUDIT table.
// It records every status transition a consent goes through.
type ConsentStatusAudit struct {
	StatusAuditID  string  `db:"STATUS_AUDIT_ID"`
	ConsentID      string  `db:"CONSENT_ID"`
	CurrentStatus  string  `db:"CURRENT_STATUS"`
	ActionTime     int64   `db:"ACTION_TIME"` // Unix ms timestamp
	Reason         *string `db:"REASON"`
	ActionBy       *string `db:"ACTION_BY"`
	PreviousStatus *string `db:"PREVIOUS_STATUS"`
	OrgID          string  `db:"ORG_ID"`
}

// =============================================================================
// Service input types — handler → service, no tags
// =============================================================================

// CreateStatusAuditInput is the input to the CreateStatusAudit service method.
// StatusAuditID and ActionTime are generated by the service.
type CreateStatusAuditInput struct {
	ConsentID      string
	CurrentStatus  string
	PreviousStatus *string
	ActionBy       *string
	Reason         *string
	OrgID          string
}

// =============================================================================
// Service return types — service → handler, no tags
// =============================================================================

// StatusAuditOutput is the service-layer representation of one audit record.
type StatusAuditOutput struct {
	StatusAuditID  string
	ConsentID      string
	CurrentStatus  string
	ActionTime     int64
	Reason         *string
	ActionBy       *string
	PreviousStatus *string
	OrgID          string
}

// ConsentStatusAuditResponse is the API response shape for a consent status audit entry.
type ConsentStatusAuditResponse struct {
	StatusAuditID  string  `json:"statusAuditId"`
	PreviousStatus *string `json:"previousStatus,omitempty"`
	CurrentStatus  string  `json:"currentStatus"`
	ActionTime     int64   `json:"actionTime"`
	ActionBy       *string `json:"actionBy,omitempty"`
	Reason         *string `json:"reason,omitempty"`
}

// ToResponse converts a status audit row to an API response row.
func (a ConsentStatusAudit) ToResponse() ConsentStatusAuditResponse {
	return ConsentStatusAuditResponse{
		StatusAuditID:  a.StatusAuditID,
		PreviousStatus: a.PreviousStatus,
		CurrentStatus:  a.CurrentStatus,
		ActionTime:     a.ActionTime,
		ActionBy:       a.ActionBy,
		Reason:         a.Reason,
	}
}
