// Code generated by mockery v2.53.5. DO NOT EDIT.

package authresource

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/wso2/openfgc/internal/authresource/model"

	serviceerror "github.com/wso2/openfgc/internal/system/error/serviceerror"
)

// MockAuthResourceService is an autogenerated mock type for the AuthResourceServiceInterface type
type MockAuthResourceService struct {
	mock.Mock
}

// CreateAuthResource provides a mock function with given fields: ctx, consentID, orgID, request
func (_m *MockAuthResourceService) CreateAuthResource(ctx context.Context, consentID string, orgID string, request *model.ConsentAuthResourceCreateRequest) (*model.ConsentAuthResourceResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, consentID, orgID, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthResource")
	}

	var r0 *model.ConsentAuthResourceResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.ConsentAuthResourceCreateRequest) (*model.ConsentAuthResourceResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, consentID, orgID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.ConsentAuthResourceCreateRequest) *model.ConsentAuthResourceResponse); ok {
		r0 = rf(ctx, consentID, orgID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentAuthResourceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *model.ConsentAuthResourceCreateRequest) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, consentID, orgID, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// GetAuthResource provides a mock function with given fields: ctx, authID, consentID, orgID
func (_m *MockAuthResourceService) GetAuthResource(ctx context.Context, authID string, consentID string, orgID string) (*model.ConsentAuthResourceResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, authID, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthResource")
	}

	var r0 *model.ConsentAuthResourceResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.ConsentAuthResourceResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, authID, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.ConsentAuthResourceResponse); ok {
		r0 = rf(ctx, authID, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentAuthResourceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, authID, consentID, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// GetAuthResourcesByConsentID provides a mock function with given fields: ctx, consentID, orgID
func (_m *MockAuthResourceService) GetAuthResourcesByConsentID(ctx context.Context, consentID string, orgID string) (*model.ConsentAuthResourceListResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, consentID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthResourcesByConsentID")
	}

	var r0 *model.ConsentAuthResourceListResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.ConsentAuthResourceListResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, consentID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.ConsentAuthResourceListResponse); ok {
		r0 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentAuthResourceListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, consentID, orgID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// UpdateAllStatusByConsentID provides a mock function with given fields: ctx, consentID, orgID, status
func (_m *MockAuthResourceService) UpdateAllStatusByConsentID(ctx context.Context, consentID string, orgID string, status string) *serviceerror.ServiceError {
	ret := _m.Called(ctx, consentID, orgID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAllStatusByConsentID")
	}

	var r0 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *serviceerror.ServiceError); ok {
		r0 = rf(ctx, consentID, orgID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}

	return r0
}

// UpdateAuthResource provides a mock function with given fields: ctx, authID, consentID, orgID, request
func (_m *MockAuthResourceService) UpdateAuthResource(ctx context.Context, authID string, consentID string, orgID string, request *model.ConsentAuthResourceUpdateRequest) (*model.ConsentAuthResourceResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, authID, consentID, orgID, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAuthResource")
	}

	var r0 *model.ConsentAuthResourceResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *model.ConsentAuthResourceUpdateRequest) (*model.ConsentAuthResourceResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, authID, consentID, orgID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *model.ConsentAuthResourceUpdateRequest) *model.ConsentAuthResourceResponse); ok {
		r0 = rf(ctx, authID, consentID, orgID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConsentAuthResourceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *model.ConsentAuthResourceUpdateRequest) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, authID, consentID, orgID, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// NewMockAuthResourceService creates a new instance of MockAuthResourceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthResourceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthResourceService {
	mock := &MockAuthResourceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
