-- Consent Management API Database Schema

-- Main consent table
CREATE TABLE IF NOT EXISTS CONSENT (
  CONSENT_ID            CHAR(36) NOT NULL,
  CREATED_TIME          BIGINT NOT NULL,
  UPDATED_TIME          BIGINT NOT NULL,
  CLIENT_ID             VARCHAR(255) NOT NULL,
  CONSENT_TYPE          VARCHAR(64) NOT NULL,
  CURRENT_STATUS        VARCHAR(64) NOT NULL,
  CONSENT_FREQUENCY     INT DEFAULT NULL,
  VALIDITY_TIME         BIGINT DEFAULT NULL,
  RECURRING_INDICATOR   BOOLEAN DEFAULT NULL,
  DATA_ACCESS_VALIDITY_DURATION BIGINT DEFAULT NULL,
  ORG_ID                VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ORG_ID),
  INDEX idx_client_id (CLIENT_ID),
  INDEX idx_consent_type (CONSENT_TYPE),
  INDEX idx_current_status (CURRENT_STATUS),
  INDEX idx_created_time (CREATED_TIME),
  INDEX idx_updated_time (UPDATED_TIME),
  INDEX idx_org_id (ORG_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Authorization resource table
CREATE TABLE IF NOT EXISTS CONSENT_AUTH_RESOURCE (
  AUTH_ID           CHAR(36) NOT NULL,
  CONSENT_ID        CHAR(36) NOT NULL,
  AUTH_TYPE         VARCHAR(255) NOT NULL,
  USER_ID           VARCHAR(255) DEFAULT NULL,
  AUTH_STATUS       VARCHAR(255) NOT NULL,
  UPDATED_TIME      BIGINT NOT NULL,
  RESOURCES                TEXT DEFAULT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (AUTH_ID, ORG_ID),
  INDEX idx_consent_id (CONSENT_ID),
  INDEX idx_user_id (USER_ID),
  INDEX idx_auth_status (AUTH_STATUS),
  INDEX idx_consent_org (CONSENT_ID, ORG_ID),
  CONSTRAINT FK_CONSENT_AUTH_RESOURCE
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Status audit table for tracking consent status changes
CREATE TABLE IF NOT EXISTS CONSENT_STATUS_AUDIT (
  STATUS_AUDIT_ID   CHAR(36) NOT NULL,
  CONSENT_ID        CHAR(36) NOT NULL,
  CURRENT_STATUS    VARCHAR(64) NOT NULL,
  ACTION_TIME       BIGINT NOT NULL,
  REASON            TEXT DEFAULT NULL,
  ACTION_BY         VARCHAR(255) DEFAULT NULL,
  PREVIOUS_STATUS   VARCHAR(64) DEFAULT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (STATUS_AUDIT_ID, ORG_ID),
  INDEX idx_consent_id (CONSENT_ID),
  INDEX idx_action_time (ACTION_TIME),
  CONSTRAINT FK_CONSENT_STATUS_AUDIT
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Consent attributes table for key-value pairs
CREATE TABLE IF NOT EXISTS CONSENT_ATTRIBUTE (
  CONSENT_ID        CHAR(36) NOT NULL,
  ATT_KEY           VARCHAR(255) NOT NULL,
  ATT_VALUE         TEXT NOT NULL,
  ORG_ID            VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ATT_KEY, ORG_ID),
  INDEX idx_att_key (ATT_KEY),
  INDEX idx_consent_org (CONSENT_ID, ORG_ID),
  CONSTRAINT FK_CONSENT_ATTRIBUTE
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Consent element table (formerly consent purpose)
CREATE TABLE IF NOT EXISTS CONSENT_ELEMENT (
  ID            CHAR(36) NOT NULL,
  NAME          VARCHAR(255) NOT NULL,
  DESCRIPTION   VARCHAR(1024) DEFAULT NULL,
  TYPE          VARCHAR(64) NOT NULL DEFAULT 'basic',
  ORG_ID        VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (ID, ORG_ID),
  UNIQUE KEY unique_name_per_org (NAME, ORG_ID),
  INDEX idx_name (NAME),
  INDEX idx_org_id (ORG_ID),
  INDEX idx_type (TYPE)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Properties for consent elements (key/value pairs scoped to element + org)
CREATE TABLE IF NOT EXISTS CONSENT_ELEMENT_PROPERTY (
  ELEMENT_ID       CHAR(36) NOT NULL,
  ATT_KEY          VARCHAR(255) NOT NULL,
  ATT_VALUE        TEXT NOT NULL,
  ORG_ID           VARCHAR(255) DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (ELEMENT_ID, ATT_KEY, ORG_ID),
  INDEX idx_att_key_element (ATT_KEY),
  CONSTRAINT FK_CONSENT_ELEMENT_PROPERTY_ELEMENT
    FOREIGN KEY (ELEMENT_ID, ORG_ID)
    REFERENCES CONSENT_ELEMENT (ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Purpose table to organize related elements with mandatory/optional flags
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE (
  ID           CHAR(36) NOT NULL,
  NAME         VARCHAR(255) NOT NULL,
  DESCRIPTION  VARCHAR(1024) DEFAULT NULL,
  CLIENT_ID    VARCHAR(255) NOT NULL,   -- purpose ownership (TPP / client)
  CREATED_TIME BIGINT NOT NULL,
  UPDATED_TIME BIGINT NOT NULL,
  ORG_ID       VARCHAR(255) DEFAULT 'DEFAULT_ORG',

  PRIMARY KEY (ID, ORG_ID),
  UNIQUE KEY uk_purpose_name_per_client (NAME, CLIENT_ID, ORG_ID),

  INDEX idx_purpose_client_id (CLIENT_ID),
  INDEX idx_purpose_org_id (ORG_ID),
  INDEX idx_purpose_name (NAME),
  INDEX idx_purpose_created_time (CREATED_TIME),
  INDEX idx_purpose_org_client (ORG_ID, CLIENT_ID)
) ENGINE=INNODB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Maps elements to purposes with mandatory flag (defines purpose structure)
CREATE TABLE IF NOT EXISTS PURPOSE_ELEMENT_MAPPING (
  PURPOSE_ID   CHAR(36) NOT NULL,
  ELEMENT_ID   CHAR(36) NOT NULL,
  IS_MANDATORY BOOLEAN NOT NULL DEFAULT FALSE,
  ORG_ID       VARCHAR(255) DEFAULT 'DEFAULT_ORG',

  PRIMARY KEY (PURPOSE_ID, ELEMENT_ID, ORG_ID),

  INDEX idx_purpose_element_purpose (PURPOSE_ID),
  INDEX idx_purpose_element_element (ELEMENT_ID),
  INDEX idx_purpose_element_org (ORG_ID),

  CONSTRAINT fk_purpose_element_purpose
    FOREIGN KEY (PURPOSE_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE (ID, ORG_ID)
    ON DELETE CASCADE,

  CONSTRAINT fk_purpose_element_element
    FOREIGN KEY (ELEMENT_ID, ORG_ID)
    REFERENCES CONSENT_ELEMENT (ID, ORG_ID)
    ON DELETE RESTRICT
) ENGINE=INNODB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS PURPOSE_CONSENT_MAPPING (
  CONSENT_ID CHAR(36) NOT NULL,
  PURPOSE_ID CHAR(36) NOT NULL,
  ORG_ID     VARCHAR(255) DEFAULT 'DEFAULT_ORG',

  PRIMARY KEY (CONSENT_ID, PURPOSE_ID, ORG_ID),

  INDEX idx_purpose_consent_consent (CONSENT_ID),
  INDEX idx_purpose_consent_purpose (PURPOSE_ID),
  INDEX idx_purpose_consent_org (ORG_ID),

  CONSTRAINT fk_purpose_consent_consent
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE,

  CONSTRAINT fk_purpose_consent_purpose
    FOREIGN KEY (PURPOSE_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE (ID, ORG_ID)
    ON DELETE RESTRICT
) ENGINE=INNODB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Stores user approval status and value for each element in a consent
-- Replaces the old CONSENT_PURPOSE_MAPPING when using purposes
CREATE TABLE IF NOT EXISTS CONSENT_ELEMENT_APPROVAL (
  CONSENT_ID       CHAR(36) NOT NULL,
  PURPOSE_ID       CHAR(36) NOT NULL,
  ELEMENT_ID       CHAR(36) NOT NULL,
  IS_USER_APPROVED BOOLEAN NOT NULL DEFAULT FALSE,
  VALUE            JSON DEFAULT NULL,  -- user-provided value for this element
  ORG_ID           VARCHAR(255) DEFAULT 'DEFAULT_ORG',

  -- One approval per element per purpose per consent
  PRIMARY KEY (CONSENT_ID, PURPOSE_ID, ELEMENT_ID, ORG_ID),

  INDEX idx_approval_consent (CONSENT_ID, ORG_ID),
  INDEX idx_approval_purpose (PURPOSE_ID, ORG_ID),
  INDEX idx_approval_element (ELEMENT_ID, ORG_ID),
  INDEX idx_approval_status (IS_USER_APPROVED),

  -- Element must belong to the purpose
  CONSTRAINT fk_approval_purpose_element
    FOREIGN KEY (PURPOSE_ID, ELEMENT_ID, ORG_ID)
    REFERENCES PURPOSE_ELEMENT_MAPPING (PURPOSE_ID, ELEMENT_ID, ORG_ID)
    ON DELETE RESTRICT,

  -- Purpose must belong to the consent
  CONSTRAINT fk_approval_consent_purpose
    FOREIGN KEY (CONSENT_ID, PURPOSE_ID, ORG_ID)
    REFERENCES PURPOSE_CONSENT_MAPPING (CONSENT_ID, PURPOSE_ID, ORG_ID)
    ON DELETE CASCADE
) ENGINE=INNODB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
