-- Consent Management API Database Schema (PostgreSQL)

-- Main consent table
CREATE TABLE IF NOT EXISTS CONSENT (
  CONSENT_ID            CHAR(36) NOT NULL,
  CREATED_TIME          BIGINT NOT NULL,
  UPDATED_TIME          BIGINT NOT NULL,
  CLIENT_ID             VARCHAR(255) NOT NULL,
  CONSENT_TYPE          VARCHAR(64) NOT NULL,
  CURRENT_STATUS        VARCHAR(64) NOT NULL,
  CONSENT_FREQUENCY     INT DEFAULT NULL,
  VALIDITY_TIME         BIGINT DEFAULT NULL,
  RECURRING_INDICATOR   BOOLEAN DEFAULT NULL,
  DATA_ACCESS_VALIDITY_DURATION BIGINT DEFAULT NULL,
  ORG_ID                VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ORG_ID)
);

CREATE INDEX IF NOT EXISTS idx_consent_client_id ON CONSENT (CLIENT_ID);
CREATE INDEX IF NOT EXISTS idx_consent_type ON CONSENT (CONSENT_TYPE);
CREATE INDEX IF NOT EXISTS idx_consent_current_status ON CONSENT (CURRENT_STATUS);
CREATE INDEX IF NOT EXISTS idx_consent_created_time ON CONSENT (CREATED_TIME);
CREATE INDEX IF NOT EXISTS idx_consent_updated_time ON CONSENT (UPDATED_TIME);
CREATE INDEX IF NOT EXISTS idx_consent_org_id ON CONSENT (ORG_ID);

-- Authorization resource table
CREATE TABLE IF NOT EXISTS CONSENT_AUTH_RESOURCE (
  AUTH_ID           CHAR(36) NOT NULL,
  CONSENT_ID        CHAR(36) NOT NULL,
  AUTH_TYPE         VARCHAR(255) NOT NULL,
  USER_ID           VARCHAR(255) DEFAULT NULL,
  AUTH_STATUS       VARCHAR(255) NOT NULL,
  UPDATED_TIME      BIGINT NOT NULL,
  RESOURCES         TEXT DEFAULT NULL,
  ORG_ID            VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (AUTH_ID, ORG_ID),
  CONSTRAINT FK_CONSENT_AUTH_RESOURCE
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_auth_resource_consent_id ON CONSENT_AUTH_RESOURCE (CONSENT_ID);
CREATE INDEX IF NOT EXISTS idx_auth_resource_user_id ON CONSENT_AUTH_RESOURCE (USER_ID);
CREATE INDEX IF NOT EXISTS idx_auth_resource_auth_status ON CONSENT_AUTH_RESOURCE (AUTH_STATUS);
CREATE INDEX IF NOT EXISTS idx_auth_resource_consent_org ON CONSENT_AUTH_RESOURCE (CONSENT_ID, ORG_ID);

-- Status audit table for tracking consent status changes
CREATE TABLE IF NOT EXISTS CONSENT_STATUS_AUDIT (
  STATUS_AUDIT_ID   CHAR(36) NOT NULL,
  CONSENT_ID        CHAR(36) NOT NULL,
  CURRENT_STATUS    VARCHAR(64) NOT NULL,
  ACTION_TIME       BIGINT NOT NULL,
  REASON            TEXT DEFAULT NULL,
  ACTION_BY         VARCHAR(255) DEFAULT NULL,
  PREVIOUS_STATUS   VARCHAR(64) DEFAULT NULL,
  ORG_ID            VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (STATUS_AUDIT_ID, ORG_ID),
  CONSTRAINT FK_CONSENT_STATUS_AUDIT
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_status_audit_consent_id ON CONSENT_STATUS_AUDIT (CONSENT_ID);
CREATE INDEX IF NOT EXISTS idx_status_audit_action_time ON CONSENT_STATUS_AUDIT (ACTION_TIME);

-- Consent attributes table for key-value pairs
CREATE TABLE IF NOT EXISTS CONSENT_ATTRIBUTE (
  CONSENT_ID        CHAR(36) NOT NULL,
  ATT_KEY           VARCHAR(255) NOT NULL,
  ATT_VALUE         TEXT NOT NULL,
  ORG_ID            VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (CONSENT_ID, ATT_KEY, ORG_ID),
  CONSTRAINT FK_CONSENT_ATTRIBUTE
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_consent_attribute_att_key ON CONSENT_ATTRIBUTE (ATT_KEY);
CREATE INDEX IF NOT EXISTS idx_consent_attribute_consent_org ON CONSENT_ATTRIBUTE (CONSENT_ID, ORG_ID);

-- Consent element table (formerly consent purpose)
CREATE TABLE IF NOT EXISTS CONSENT_ELEMENT (
  ID            CHAR(36) NOT NULL,
  NAME          VARCHAR(255) NOT NULL,
  DESCRIPTION   VARCHAR(1024) DEFAULT NULL,
  TYPE          VARCHAR(64) NOT NULL DEFAULT 'basic',
  ORG_ID        VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (ID, ORG_ID),
  UNIQUE (NAME, ORG_ID)
);

CREATE INDEX IF NOT EXISTS idx_element_name ON CONSENT_ELEMENT (NAME);
CREATE INDEX IF NOT EXISTS idx_element_org_id ON CONSENT_ELEMENT (ORG_ID);
CREATE INDEX IF NOT EXISTS idx_element_type ON CONSENT_ELEMENT (TYPE);

-- Properties for consent elements (key/value pairs scoped to element + org)
CREATE TABLE IF NOT EXISTS CONSENT_ELEMENT_PROPERTY (
  ELEMENT_ID       CHAR(36) NOT NULL,
  ATT_KEY          VARCHAR(255) NOT NULL,
  ATT_VALUE        TEXT NOT NULL,
  ORG_ID           VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',
  PRIMARY KEY (ELEMENT_ID, ATT_KEY, ORG_ID),
  CONSTRAINT FK_CONSENT_ELEMENT_PROPERTY_ELEMENT
    FOREIGN KEY (ELEMENT_ID, ORG_ID)
    REFERENCES CONSENT_ELEMENT (ID, ORG_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_element_property_att_key ON CONSENT_ELEMENT_PROPERTY (ATT_KEY);

-- Purpose table to organize related elements with mandatory/optional flags
CREATE TABLE IF NOT EXISTS CONSENT_PURPOSE (
  ID           CHAR(36) NOT NULL,
  NAME         VARCHAR(255) NOT NULL,
  DESCRIPTION  VARCHAR(1024) DEFAULT NULL,
  CLIENT_ID    VARCHAR(255) NOT NULL,
  CREATED_TIME BIGINT NOT NULL,
  UPDATED_TIME BIGINT NOT NULL,
  ORG_ID       VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',

  PRIMARY KEY (ID, ORG_ID),
  UNIQUE (NAME, CLIENT_ID, ORG_ID)
);

CREATE INDEX IF NOT EXISTS idx_purpose_client_id ON CONSENT_PURPOSE (CLIENT_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_org_id ON CONSENT_PURPOSE (ORG_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_name ON CONSENT_PURPOSE (NAME);
CREATE INDEX IF NOT EXISTS idx_purpose_created_time ON CONSENT_PURPOSE (CREATED_TIME);
CREATE INDEX IF NOT EXISTS idx_purpose_org_client ON CONSENT_PURPOSE (ORG_ID, CLIENT_ID);

-- Maps elements to purposes with mandatory flag (defines purpose structure)
CREATE TABLE IF NOT EXISTS PURPOSE_ELEMENT_MAPPING (
  PURPOSE_ID   CHAR(36) NOT NULL,
  ELEMENT_ID   CHAR(36) NOT NULL,
  IS_MANDATORY BOOLEAN NOT NULL DEFAULT FALSE,
  ORG_ID       VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',

  PRIMARY KEY (PURPOSE_ID, ELEMENT_ID, ORG_ID),

  CONSTRAINT fk_purpose_element_purpose
    FOREIGN KEY (PURPOSE_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE (ID, ORG_ID)
    ON DELETE CASCADE,

  CONSTRAINT fk_purpose_element_element
    FOREIGN KEY (ELEMENT_ID, ORG_ID)
    REFERENCES CONSENT_ELEMENT (ID, ORG_ID)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_purpose_element_purpose ON PURPOSE_ELEMENT_MAPPING (PURPOSE_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_element_element ON PURPOSE_ELEMENT_MAPPING (ELEMENT_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_element_org ON PURPOSE_ELEMENT_MAPPING (ORG_ID);

CREATE TABLE IF NOT EXISTS PURPOSE_CONSENT_MAPPING (
  CONSENT_ID CHAR(36) NOT NULL,
  PURPOSE_ID CHAR(36) NOT NULL,
  ORG_ID     VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',

  PRIMARY KEY (CONSENT_ID, PURPOSE_ID, ORG_ID),

  CONSTRAINT fk_purpose_consent_consent
    FOREIGN KEY (CONSENT_ID, ORG_ID)
    REFERENCES CONSENT (CONSENT_ID, ORG_ID)
    ON DELETE CASCADE,

  CONSTRAINT fk_purpose_consent_purpose
    FOREIGN KEY (PURPOSE_ID, ORG_ID)
    REFERENCES CONSENT_PURPOSE (ID, ORG_ID)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_purpose_consent_consent ON PURPOSE_CONSENT_MAPPING (CONSENT_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_consent_purpose ON PURPOSE_CONSENT_MAPPING (PURPOSE_ID);
CREATE INDEX IF NOT EXISTS idx_purpose_consent_org ON PURPOSE_CONSENT_MAPPING (ORG_ID);

-- Stores user approval status and value for each element in a consent
-- Replaces the old CONSENT_PURPOSE_MAPPING when using purposes
CREATE TABLE IF NOT EXISTS CONSENT_ELEMENT_APPROVAL (
  CONSENT_ID       CHAR(36) NOT NULL,
  PURPOSE_ID       CHAR(36) NOT NULL,
  ELEMENT_ID       CHAR(36) NOT NULL,
  IS_USER_APPROVED BOOLEAN NOT NULL DEFAULT FALSE,
  VALUE            JSONB DEFAULT NULL,
  ORG_ID           VARCHAR(255) NOT NULL DEFAULT 'DEFAULT_ORG',

  PRIMARY KEY (CONSENT_ID, PURPOSE_ID, ELEMENT_ID, ORG_ID),

  CONSTRAINT fk_approval_purpose_element
    FOREIGN KEY (PURPOSE_ID, ELEMENT_ID, ORG_ID)
    REFERENCES PURPOSE_ELEMENT_MAPPING (PURPOSE_ID, ELEMENT_ID, ORG_ID)
    ON DELETE RESTRICT,

  CONSTRAINT fk_approval_consent_purpose
    FOREIGN KEY (CONSENT_ID, PURPOSE_ID, ORG_ID)
    REFERENCES PURPOSE_CONSENT_MAPPING (CONSENT_ID, PURPOSE_ID, ORG_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_approval_consent ON CONSENT_ELEMENT_APPROVAL (CONSENT_ID, ORG_ID);
CREATE INDEX IF NOT EXISTS idx_approval_purpose ON CONSENT_ELEMENT_APPROVAL (PURPOSE_ID, ORG_ID);
CREATE INDEX IF NOT EXISTS idx_approval_element ON CONSENT_ELEMENT_APPROVAL (ELEMENT_ID, ORG_ID);
CREATE INDEX IF NOT EXISTS idx_approval_status ON CONSENT_ELEMENT_APPROVAL (IS_USER_APPROVED);
